apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - udr-deployment.yaml
  - udr-service.yaml

configMapGenerator:
  - name: udr-configmap
    behavior: create
    files:
      - udrcfg.yaml

generatorOptions:
  disableNameSuffixHash: true
