apiVersion: v1
kind: ConfigMap
metadata:
  name: scp-configmap
  labels:
    app: open5gs
    nf: scp
data:
  scpcfg.yaml: |

    logger:
      file: /open5gs/install/var/log/open5gs/scp.log

    global:
      max:
        ue: 1024

    scp:
      sbi:
        server:
          - dev: eth0
            advertise: scp-nscp
            port: 80
        client:
          nrf:
            - uri: http://nrf-nnrf:80
      no_sepp: true
