apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - scp-deployment.yaml
  - scp-service.yaml

configMapGenerator:
  - name: scp-configmap
    behavior: create
    files:
      - scpcfg.yaml

generatorOptions:
  disableNameSuffixHash: true
