kpi:
  slice_throughput:
    enabled: true
    unit: Throughput (Mbps)
    scale_factor: 1000000
    path: data/cloud_gaming/slice_throughput.csv
  upf_cpu_usage:
    enabled: false
    unit: CPU Usage
    scale_factor: 1
    path: data/cloud_gaming/upf_cpu_usage.csv
  upf_mem_usage:
    enabled: false
    unit: Memory Usage (MB)
    scale_factor: 1000000
    path: data/cloud_gaming/upf_mem_usage.csv
  upf_energy_usage:
    enabled: false
    unit: Energy Usage (J)
    scale_factor: 1
    path: data/cloud_gaming/upf_energy_usage.csv

schemes:
  ff5: true
  ff10: true
  adaptive: true

plots:
  timeseries: true
  distribution: false
  error_timeseries: false
  error_timeseries_smooth: false
  error_distribution: false
  psd: false
