apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-configmap
  labels:
    app: open5gs
data:
  nssfcfg.yaml: |
    logger:
      file: /open5gs/install/var/log/open5gs/nssf.log

    global:
      max:
        ue: 1024

    nssf:
      sbi:
        server:
          - dev: eth0
            advertise: nssf-nnssf
            port: 80
        client:
          scp:
            - uri: http://scp-nscp:80
          nsi:
            - uri: http://nrf-nnrf:80
              s_nssai:
                sst: 1
                sd: 000001
            - uri: http://nrf-nnrf:80
              s_nssai:
                sst: 2
                sd: 000002
