// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package value

type UPF struct {
	// Affinity corresponds to the JSON schema field "affinity".
	Affinity map[string]interface{} `json:"affinity,omitempty" yaml:"affinity,omitempty" mapstructure:"affinity,omitempty"`

	// Args corresponds to the JSON schema field "args".
	Args []interface{} `json:"args,omitempty" yaml:"args,omitempty" mapstructure:"args,omitempty"`

	// Command corresponds to the JSON schema field "command".
	Command []interface{} `json:"command,omitempty" yaml:"command,omitempty" mapstructure:"command,omitempty"`

	// CommonAnnotations corresponds to the JSON schema field "commonAnnotations".
	CommonAnnotations map[string]interface{} `json:"commonAnnotations,omitempty" yaml:"commonAnnotations,omitempty" mapstructure:"commonAnnotations,omitempty"`

	// CommonLabels corresponds to the JSON schema field "commonLabels".
	CommonLabels map[string]interface{} `json:"commonLabels,omitempty" yaml:"commonLabels,omitempty" mapstructure:"commonLabels,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config *UPFConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// ContainerPorts corresponds to the JSON schema field "containerPorts".
	ContainerPorts *UPFContainerPorts `json:"containerPorts,omitempty" yaml:"containerPorts,omitempty" mapstructure:"containerPorts,omitempty"`

	// ContainerSecurityContext corresponds to the JSON schema field
	// "containerSecurityContext".
	ContainerSecurityContext *UPFContainerSecurityContext `json:"containerSecurityContext,omitempty" yaml:"containerSecurityContext,omitempty" mapstructure:"containerSecurityContext,omitempty"`

	// CustomLivenessProbe corresponds to the JSON schema field "customLivenessProbe".
	CustomLivenessProbe map[string]interface{} `json:"customLivenessProbe,omitempty" yaml:"customLivenessProbe,omitempty" mapstructure:"customLivenessProbe,omitempty"`

	// CustomOpen5GsConfig corresponds to the JSON schema field "customOpen5gsConfig".
	CustomOpen5GsConfig map[string]interface{} `json:"customOpen5gsConfig,omitempty" yaml:"customOpen5gsConfig,omitempty" mapstructure:"customOpen5gsConfig,omitempty"`

	// CustomReadinessProbe corresponds to the JSON schema field
	// "customReadinessProbe".
	CustomReadinessProbe map[string]interface{} `json:"customReadinessProbe,omitempty" yaml:"customReadinessProbe,omitempty" mapstructure:"customReadinessProbe,omitempty"`

	// CustomStartupProbe corresponds to the JSON schema field "customStartupProbe".
	CustomStartupProbe map[string]interface{} `json:"customStartupProbe,omitempty" yaml:"customStartupProbe,omitempty" mapstructure:"customStartupProbe,omitempty"`

	// ExtraDeploy corresponds to the JSON schema field "extraDeploy".
	ExtraDeploy []interface{} `json:"extraDeploy,omitempty" yaml:"extraDeploy,omitempty" mapstructure:"extraDeploy,omitempty"`

	// ExtraEnvVars corresponds to the JSON schema field "extraEnvVars".
	ExtraEnvVars []interface{} `json:"extraEnvVars,omitempty" yaml:"extraEnvVars,omitempty" mapstructure:"extraEnvVars,omitempty"`

	// ExtraEnvVarsCM corresponds to the JSON schema field "extraEnvVarsCM".
	ExtraEnvVarsCM *string `json:"extraEnvVarsCM,omitempty" yaml:"extraEnvVarsCM,omitempty" mapstructure:"extraEnvVarsCM,omitempty"`

	// ExtraEnvVarsSecret corresponds to the JSON schema field "extraEnvVarsSecret".
	ExtraEnvVarsSecret *string `json:"extraEnvVarsSecret,omitempty" yaml:"extraEnvVarsSecret,omitempty" mapstructure:"extraEnvVarsSecret,omitempty"`

	// ExtraVolumeMounts corresponds to the JSON schema field "extraVolumeMounts".
	ExtraVolumeMounts []interface{} `json:"extraVolumeMounts,omitempty" yaml:"extraVolumeMounts,omitempty" mapstructure:"extraVolumeMounts,omitempty"`

	// ExtraVolumes corresponds to the JSON schema field "extraVolumes".
	ExtraVolumes []interface{} `json:"extraVolumes,omitempty" yaml:"extraVolumes,omitempty" mapstructure:"extraVolumes,omitempty"`

	// FullnameOverride corresponds to the JSON schema field "fullnameOverride".
	FullnameOverride *string `json:"fullnameOverride,omitempty" yaml:"fullnameOverride,omitempty" mapstructure:"fullnameOverride,omitempty"`

	// Global corresponds to the JSON schema field "global".
	Global *UPFGlobal `json:"global,omitempty" yaml:"global,omitempty" mapstructure:"global,omitempty"`

	// HostAliases corresponds to the JSON schema field "hostAliases".
	HostAliases []interface{} `json:"hostAliases,omitempty" yaml:"hostAliases,omitempty" mapstructure:"hostAliases,omitempty"`

	// Image corresponds to the JSON schema field "image".
	Image *UPFImage `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// InitContainers corresponds to the JSON schema field "initContainers".
	InitContainers []interface{} `json:"initContainers,omitempty" yaml:"initContainers,omitempty" mapstructure:"initContainers,omitempty"`

	// KubeVersion corresponds to the JSON schema field "kubeVersion".
	KubeVersion *string `json:"kubeVersion,omitempty" yaml:"kubeVersion,omitempty" mapstructure:"kubeVersion,omitempty"`

	// LifecycleHooks corresponds to the JSON schema field "lifecycleHooks".
	LifecycleHooks map[string]interface{} `json:"lifecycleHooks,omitempty" yaml:"lifecycleHooks,omitempty" mapstructure:"lifecycleHooks,omitempty"`

	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *UPFMetrics `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// NameOverride corresponds to the JSON schema field "nameOverride".
	NameOverride *string `json:"nameOverride,omitempty" yaml:"nameOverride,omitempty" mapstructure:"nameOverride,omitempty"`

	// NamespaceOverride corresponds to the JSON schema field "namespaceOverride".
	NamespaceOverride *string `json:"namespaceOverride,omitempty" yaml:"namespaceOverride,omitempty" mapstructure:"namespaceOverride,omitempty"`

	// NodeAffinityPreset corresponds to the JSON schema field "nodeAffinityPreset".
	NodeAffinityPreset *UPFNodeAffinityPreset `json:"nodeAffinityPreset,omitempty" yaml:"nodeAffinityPreset,omitempty" mapstructure:"nodeAffinityPreset,omitempty"`

	// NodeSelector corresponds to the JSON schema field "nodeSelector".
	NodeSelector map[string]interface{} `json:"nodeSelector,omitempty" yaml:"nodeSelector,omitempty" mapstructure:"nodeSelector,omitempty"`

	// Open5GsSmf corresponds to the JSON schema field "open5gs-smf".
	Open5GsSmf *UPFOpen5GsSmf `json:"open5gs-smf,omitempty" yaml:"open5gs-smf,omitempty" mapstructure:"open5gs-smf,omitempty"`

	// PodAffinityPreset corresponds to the JSON schema field "podAffinityPreset".
	PodAffinityPreset *string `json:"podAffinityPreset,omitempty" yaml:"podAffinityPreset,omitempty" mapstructure:"podAffinityPreset,omitempty"`

	// PodAnnotations corresponds to the JSON schema field "podAnnotations".
	PodAnnotations map[string]interface{} `json:"podAnnotations,omitempty" yaml:"podAnnotations,omitempty" mapstructure:"podAnnotations,omitempty"`

	// PodAntiAffinityPreset corresponds to the JSON schema field
	// "podAntiAffinityPreset".
	PodAntiAffinityPreset *string `json:"podAntiAffinityPreset,omitempty" yaml:"podAntiAffinityPreset,omitempty" mapstructure:"podAntiAffinityPreset,omitempty"`

	// PodLabels corresponds to the JSON schema field "podLabels".
	PodLabels map[string]interface{} `json:"podLabels,omitempty" yaml:"podLabels,omitempty" mapstructure:"podLabels,omitempty"`

	// PodSecurityContext corresponds to the JSON schema field "podSecurityContext".
	PodSecurityContext *UPFPodSecurityContext `json:"podSecurityContext,omitempty" yaml:"podSecurityContext,omitempty" mapstructure:"podSecurityContext,omitempty"`

	// PriorityClassName corresponds to the JSON schema field "priorityClassName".
	PriorityClassName *string `json:"priorityClassName,omitempty" yaml:"priorityClassName,omitempty" mapstructure:"priorityClassName,omitempty"`

	// ReplicaCount corresponds to the JSON schema field "replicaCount".
	ReplicaCount *int `json:"replicaCount,omitempty" yaml:"replicaCount,omitempty" mapstructure:"replicaCount,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *UPFResources `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// SchedulerName corresponds to the JSON schema field "schedulerName".
	SchedulerName *string `json:"schedulerName,omitempty" yaml:"schedulerName,omitempty" mapstructure:"schedulerName,omitempty"`

	// ServiceAccount corresponds to the JSON schema field "serviceAccount".
	ServiceAccount *UPFServiceAccount `json:"serviceAccount,omitempty" yaml:"serviceAccount,omitempty" mapstructure:"serviceAccount,omitempty"`

	// Services corresponds to the JSON schema field "services".
	Services *UPFServices `json:"services,omitempty" yaml:"services,omitempty" mapstructure:"services,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// Sidecars corresponds to the JSON schema field "sidecars".
	Sidecars []interface{} `json:"sidecars,omitempty" yaml:"sidecars,omitempty" mapstructure:"sidecars,omitempty"`

	// Tolerations corresponds to the JSON schema field "tolerations".
	Tolerations []interface{} `json:"tolerations,omitempty" yaml:"tolerations,omitempty" mapstructure:"tolerations,omitempty"`

	// TopologySpreadConstraints corresponds to the JSON schema field
	// "topologySpreadConstraints".
	TopologySpreadConstraints []interface{} `json:"topologySpreadConstraints,omitempty" yaml:"topologySpreadConstraints,omitempty" mapstructure:"topologySpreadConstraints,omitempty"`

	// UpdateStrategy corresponds to the JSON schema field "updateStrategy".
	UpdateStrategy *UPFUpdateStrategy `json:"updateStrategy,omitempty" yaml:"updateStrategy,omitempty" mapstructure:"updateStrategy,omitempty"`
}

type UPFConfig struct {
	// LogLevel corresponds to the JSON schema field "logLevel".
	LogLevel *string `json:"logLevel,omitempty" yaml:"logLevel,omitempty" mapstructure:"logLevel,omitempty"`

	// SubnetList corresponds to the JSON schema field "subnetList".
	SubnetList []UPFConfigSubnetListElem `json:"subnetList,omitempty" yaml:"subnetList,omitempty" mapstructure:"subnetList,omitempty"`

	// Upf corresponds to the JSON schema field "upf".
	Upf *UPFConfigUpf `json:"upf,omitempty" yaml:"upf,omitempty" mapstructure:"upf,omitempty"`
}

type UPFConfigSubnetListElem struct {
	// CreateDev corresponds to the JSON schema field "createDev".
	CreateDev *bool `json:"createDev,omitempty" yaml:"createDev,omitempty" mapstructure:"createDev,omitempty"`

	// Dev corresponds to the JSON schema field "dev".
	Dev *string `json:"dev,omitempty" yaml:"dev,omitempty" mapstructure:"dev,omitempty"`

	// Dnn corresponds to the JSON schema field "dnn".
	Dnn *string `json:"dnn,omitempty" yaml:"dnn,omitempty" mapstructure:"dnn,omitempty"`

	// EnableNAT corresponds to the JSON schema field "enableNAT".
	EnableNAT *bool `json:"enableNAT,omitempty" yaml:"enableNAT,omitempty" mapstructure:"enableNAT,omitempty"`

	// Gateway corresponds to the JSON schema field "gateway".
	Gateway *string `json:"gateway,omitempty" yaml:"gateway,omitempty" mapstructure:"gateway,omitempty"`

	// Mask corresponds to the JSON schema field "mask".
	Mask *int `json:"mask,omitempty" yaml:"mask,omitempty" mapstructure:"mask,omitempty"`

	// Subnet corresponds to the JSON schema field "subnet".
	Subnet *string `json:"subnet,omitempty" yaml:"subnet,omitempty" mapstructure:"subnet,omitempty"`
}

type UPFConfigUpf struct {
	// Gtpu corresponds to the JSON schema field "gtpu".
	Gtpu *UPFConfigUpfGtpu `json:"gtpu,omitempty" yaml:"gtpu,omitempty" mapstructure:"gtpu,omitempty"`
}

type UPFConfigUpfGtpu struct {
	// Advertise corresponds to the JSON schema field "advertise".
	Advertise *string `json:"advertise,omitempty" yaml:"advertise,omitempty" mapstructure:"advertise,omitempty"`

	// Dev corresponds to the JSON schema field "dev".
	Dev *string `json:"dev,omitempty" yaml:"dev,omitempty" mapstructure:"dev,omitempty"`
}

type UPFContainerPorts struct {
	// Gtpu corresponds to the JSON schema field "gtpu".
	Gtpu *int `json:"gtpu,omitempty" yaml:"gtpu,omitempty" mapstructure:"gtpu,omitempty"`

	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *int `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// Pfcp corresponds to the JSON schema field "pfcp".
	Pfcp *int `json:"pfcp,omitempty" yaml:"pfcp,omitempty" mapstructure:"pfcp,omitempty"`
}

type UPFContainerSecurityContext struct {
	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities *UPFContainerSecurityContextCapabilities `json:"capabilities,omitempty" yaml:"capabilities,omitempty" mapstructure:"capabilities,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Privileged corresponds to the JSON schema field "privileged".
	Privileged *bool `json:"privileged,omitempty" yaml:"privileged,omitempty" mapstructure:"privileged,omitempty"`

	// RunAsNonRoot corresponds to the JSON schema field "runAsNonRoot".
	RunAsNonRoot *bool `json:"runAsNonRoot,omitempty" yaml:"runAsNonRoot,omitempty" mapstructure:"runAsNonRoot,omitempty"`
}

type UPFContainerSecurityContextCapabilities struct {
	// Add corresponds to the JSON schema field "add".
	Add []string `json:"add,omitempty" yaml:"add,omitempty" mapstructure:"add,omitempty"`
}

type UPFGlobal struct {
	// ImagePullSecrets corresponds to the JSON schema field "imagePullSecrets".
	ImagePullSecrets []interface{} `json:"imagePullSecrets,omitempty" yaml:"imagePullSecrets,omitempty" mapstructure:"imagePullSecrets,omitempty"`

	// ImageRegistry corresponds to the JSON schema field "imageRegistry".
	ImageRegistry *string `json:"imageRegistry,omitempty" yaml:"imageRegistry,omitempty" mapstructure:"imageRegistry,omitempty"`

	// StorageClass corresponds to the JSON schema field "storageClass".
	StorageClass *string `json:"storageClass,omitempty" yaml:"storageClass,omitempty" mapstructure:"storageClass,omitempty"`
}

type UPFImage struct {
	// Debug corresponds to the JSON schema field "debug".
	Debug *bool `json:"debug,omitempty" yaml:"debug,omitempty" mapstructure:"debug,omitempty"`

	// Digest corresponds to the JSON schema field "digest".
	Digest *string `json:"digest,omitempty" yaml:"digest,omitempty" mapstructure:"digest,omitempty"`

	// PullPolicy corresponds to the JSON schema field "pullPolicy".
	PullPolicy *string `json:"pullPolicy,omitempty" yaml:"pullPolicy,omitempty" mapstructure:"pullPolicy,omitempty"`

	// PullSecrets corresponds to the JSON schema field "pullSecrets".
	PullSecrets []interface{} `json:"pullSecrets,omitempty" yaml:"pullSecrets,omitempty" mapstructure:"pullSecrets,omitempty"`

	// Registry corresponds to the JSON schema field "registry".
	Registry *string `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository *string `json:"repository,omitempty" yaml:"repository,omitempty" mapstructure:"repository,omitempty"`

	// Tag corresponds to the JSON schema field "tag".
	Tag *string `json:"tag,omitempty" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`
}

type UPFMetrics struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// ServiceMonitor corresponds to the JSON schema field "serviceMonitor".
	ServiceMonitor *UPFMetricsServiceMonitor `json:"serviceMonitor,omitempty" yaml:"serviceMonitor,omitempty" mapstructure:"serviceMonitor,omitempty"`

	// ServiceScrape corresponds to the JSON schema field "serviceScrape".
	ServiceScrape *UPFMetricsServiceScrape `json:"serviceScrape,omitempty" yaml:"serviceScrape,omitempty" mapstructure:"serviceScrape,omitempty"`
}

type UPFMetricsServiceMonitor struct {
	// AdditionalLabels corresponds to the JSON schema field "additionalLabels".
	AdditionalLabels map[string]interface{} `json:"additionalLabels,omitempty" yaml:"additionalLabels,omitempty" mapstructure:"additionalLabels,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// HonorLabels corresponds to the JSON schema field "honorLabels".
	HonorLabels *bool `json:"honorLabels,omitempty" yaml:"honorLabels,omitempty" mapstructure:"honorLabels,omitempty"`

	// Interval corresponds to the JSON schema field "interval".
	Interval *string `json:"interval,omitempty" yaml:"interval,omitempty" mapstructure:"interval,omitempty"`

	// MetricRelabelings corresponds to the JSON schema field "metricRelabelings".
	MetricRelabelings []interface{} `json:"metricRelabelings,omitempty" yaml:"metricRelabelings,omitempty" mapstructure:"metricRelabelings,omitempty"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Relabelings corresponds to the JSON schema field "relabelings".
	Relabelings []interface{} `json:"relabelings,omitempty" yaml:"relabelings,omitempty" mapstructure:"relabelings,omitempty"`

	// ScrapeTimeout corresponds to the JSON schema field "scrapeTimeout".
	ScrapeTimeout *string `json:"scrapeTimeout,omitempty" yaml:"scrapeTimeout,omitempty" mapstructure:"scrapeTimeout,omitempty"`
}

type UPFMetricsServiceScrape struct {
	// AdditionalLabels corresponds to the JSON schema field "additionalLabels".
	AdditionalLabels map[string]interface{} `json:"additionalLabels,omitempty" yaml:"additionalLabels,omitempty" mapstructure:"additionalLabels,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// ScrapeInterval corresponds to the JSON schema field "scrape_interval".
	ScrapeInterval *string `json:"scrape_interval,omitempty" yaml:"scrape_interval,omitempty" mapstructure:"scrape_interval,omitempty"`
}

type UPFNodeAffinityPreset struct {
	// Key corresponds to the JSON schema field "key".
	Key *string `json:"key,omitempty" yaml:"key,omitempty" mapstructure:"key,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// Values corresponds to the JSON schema field "values".
	Values []interface{} `json:"values,omitempty" yaml:"values,omitempty" mapstructure:"values,omitempty"`
}

type UPFOpen5GsSmf struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`
}

type UPFPodSecurityContext struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FsGroup corresponds to the JSON schema field "fsGroup".
	FsGroup *int `json:"fsGroup,omitempty" yaml:"fsGroup,omitempty" mapstructure:"fsGroup,omitempty"`
}

type UPFResources struct {
	// Limits corresponds to the JSON schema field "limits".
	Limits map[string]interface{} `json:"limits,omitempty" yaml:"limits,omitempty" mapstructure:"limits,omitempty"`

	// Requests corresponds to the JSON schema field "requests".
	Requests map[string]interface{} `json:"requests,omitempty" yaml:"requests,omitempty" mapstructure:"requests,omitempty"`
}

type UPFServiceAccount struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations map[string]interface{} `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// AutomountServiceAccountToken corresponds to the JSON schema field
	// "automountServiceAccountToken".
	AutomountServiceAccountToken *bool `json:"automountServiceAccountToken,omitempty" yaml:"automountServiceAccountToken,omitempty" mapstructure:"automountServiceAccountToken,omitempty"`

	// Create corresponds to the JSON schema field "create".
	Create *bool `json:"create,omitempty" yaml:"create,omitempty" mapstructure:"create,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type UPFServices struct {
	// Gtpu corresponds to the JSON schema field "gtpu".
	Gtpu *UPFServicesGtpu `json:"gtpu,omitempty" yaml:"gtpu,omitempty" mapstructure:"gtpu,omitempty"`

	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *UPFServicesMetrics `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// Pfcp corresponds to the JSON schema field "pfcp".
	Pfcp *UPFServicesPfcp `json:"pfcp,omitempty" yaml:"pfcp,omitempty" mapstructure:"pfcp,omitempty"`
}

type UPFServicesGtpu struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations map[string]interface{} `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// ClusterIP corresponds to the JSON schema field "clusterIP".
	ClusterIP *string `json:"clusterIP,omitempty" yaml:"clusterIP,omitempty" mapstructure:"clusterIP,omitempty"`

	// ExternalTrafficPolicy corresponds to the JSON schema field
	// "externalTrafficPolicy".
	ExternalTrafficPolicy *string `json:"externalTrafficPolicy,omitempty" yaml:"externalTrafficPolicy,omitempty" mapstructure:"externalTrafficPolicy,omitempty"`

	// ExtraPorts corresponds to the JSON schema field "extraPorts".
	ExtraPorts []interface{} `json:"extraPorts,omitempty" yaml:"extraPorts,omitempty" mapstructure:"extraPorts,omitempty"`

	// LoadBalancerIP corresponds to the JSON schema field "loadBalancerIP".
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty" yaml:"loadBalancerIP,omitempty" mapstructure:"loadBalancerIP,omitempty"`

	// LoadBalancerSourceRanges corresponds to the JSON schema field
	// "loadBalancerSourceRanges".
	LoadBalancerSourceRanges []interface{} `json:"loadBalancerSourceRanges,omitempty" yaml:"loadBalancerSourceRanges,omitempty" mapstructure:"loadBalancerSourceRanges,omitempty"`

	// NodePorts corresponds to the JSON schema field "nodePorts".
	NodePorts *UPFServicesGtpuNodePorts `json:"nodePorts,omitempty" yaml:"nodePorts,omitempty" mapstructure:"nodePorts,omitempty"`

	// Ports corresponds to the JSON schema field "ports".
	Ports *UPFServicesGtpuPorts `json:"ports,omitempty" yaml:"ports,omitempty" mapstructure:"ports,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// SessionAffinityConfig corresponds to the JSON schema field
	// "sessionAffinityConfig".
	SessionAffinityConfig map[string]interface{} `json:"sessionAffinityConfig,omitempty" yaml:"sessionAffinityConfig,omitempty" mapstructure:"sessionAffinityConfig,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type UPFServicesGtpuNodePorts struct {
	// Gtpu corresponds to the JSON schema field "gtpu".
	Gtpu *string `json:"gtpu,omitempty" yaml:"gtpu,omitempty" mapstructure:"gtpu,omitempty"`
}

type UPFServicesGtpuPorts struct {
	// Gtpu corresponds to the JSON schema field "gtpu".
	Gtpu *int `json:"gtpu,omitempty" yaml:"gtpu,omitempty" mapstructure:"gtpu,omitempty"`
}

type UPFServicesMetrics struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations *UPFServicesMetricsAnnotations `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// ClusterIP corresponds to the JSON schema field "clusterIP".
	ClusterIP *string `json:"clusterIP,omitempty" yaml:"clusterIP,omitempty" mapstructure:"clusterIP,omitempty"`

	// ExternalTrafficPolicy corresponds to the JSON schema field
	// "externalTrafficPolicy".
	ExternalTrafficPolicy *string `json:"externalTrafficPolicy,omitempty" yaml:"externalTrafficPolicy,omitempty" mapstructure:"externalTrafficPolicy,omitempty"`

	// ExtraPorts corresponds to the JSON schema field "extraPorts".
	ExtraPorts []interface{} `json:"extraPorts,omitempty" yaml:"extraPorts,omitempty" mapstructure:"extraPorts,omitempty"`

	// LoadBalancerIP corresponds to the JSON schema field "loadBalancerIP".
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty" yaml:"loadBalancerIP,omitempty" mapstructure:"loadBalancerIP,omitempty"`

	// LoadBalancerSourceRanges corresponds to the JSON schema field
	// "loadBalancerSourceRanges".
	LoadBalancerSourceRanges []interface{} `json:"loadBalancerSourceRanges,omitempty" yaml:"loadBalancerSourceRanges,omitempty" mapstructure:"loadBalancerSourceRanges,omitempty"`

	// NodePorts corresponds to the JSON schema field "nodePorts".
	NodePorts *UPFServicesMetricsNodePorts `json:"nodePorts,omitempty" yaml:"nodePorts,omitempty" mapstructure:"nodePorts,omitempty"`

	// Ports corresponds to the JSON schema field "ports".
	Ports *UPFServicesMetricsPorts `json:"ports,omitempty" yaml:"ports,omitempty" mapstructure:"ports,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// SessionAffinityConfig corresponds to the JSON schema field
	// "sessionAffinityConfig".
	SessionAffinityConfig map[string]interface{} `json:"sessionAffinityConfig,omitempty" yaml:"sessionAffinityConfig,omitempty" mapstructure:"sessionAffinityConfig,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type UPFServicesMetricsAnnotations struct {
	// PrometheusIoPath corresponds to the JSON schema field "prometheus.io/path".
	PrometheusIoPath *string `json:"prometheus.io/path,omitempty" yaml:"prometheus.io/path,omitempty" mapstructure:"prometheus.io/path,omitempty"`
}

type UPFServicesMetricsNodePorts struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *string `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`
}

type UPFServicesMetricsPorts struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *int `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`
}

type UPFServicesPfcp struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations map[string]interface{} `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// ClusterIP corresponds to the JSON schema field "clusterIP".
	ClusterIP *string `json:"clusterIP,omitempty" yaml:"clusterIP,omitempty" mapstructure:"clusterIP,omitempty"`

	// ExternalTrafficPolicy corresponds to the JSON schema field
	// "externalTrafficPolicy".
	ExternalTrafficPolicy *string `json:"externalTrafficPolicy,omitempty" yaml:"externalTrafficPolicy,omitempty" mapstructure:"externalTrafficPolicy,omitempty"`

	// ExtraPorts corresponds to the JSON schema field "extraPorts".
	ExtraPorts []interface{} `json:"extraPorts,omitempty" yaml:"extraPorts,omitempty" mapstructure:"extraPorts,omitempty"`

	// LoadBalancerIP corresponds to the JSON schema field "loadBalancerIP".
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty" yaml:"loadBalancerIP,omitempty" mapstructure:"loadBalancerIP,omitempty"`

	// LoadBalancerSourceRanges corresponds to the JSON schema field
	// "loadBalancerSourceRanges".
	LoadBalancerSourceRanges []interface{} `json:"loadBalancerSourceRanges,omitempty" yaml:"loadBalancerSourceRanges,omitempty" mapstructure:"loadBalancerSourceRanges,omitempty"`

	// NodePorts corresponds to the JSON schema field "nodePorts".
	NodePorts *UPFServicesPfcpNodePorts `json:"nodePorts,omitempty" yaml:"nodePorts,omitempty" mapstructure:"nodePorts,omitempty"`

	// Ports corresponds to the JSON schema field "ports".
	Ports *UPFServicesPfcpPorts `json:"ports,omitempty" yaml:"ports,omitempty" mapstructure:"ports,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// SessionAffinityConfig corresponds to the JSON schema field
	// "sessionAffinityConfig".
	SessionAffinityConfig map[string]interface{} `json:"sessionAffinityConfig,omitempty" yaml:"sessionAffinityConfig,omitempty" mapstructure:"sessionAffinityConfig,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type UPFServicesPfcpNodePorts struct {
	// Pfcp corresponds to the JSON schema field "pfcp".
	Pfcp *string `json:"pfcp,omitempty" yaml:"pfcp,omitempty" mapstructure:"pfcp,omitempty"`
}

type UPFServicesPfcpPorts struct {
	// Pfcp corresponds to the JSON schema field "pfcp".
	Pfcp *int `json:"pfcp,omitempty" yaml:"pfcp,omitempty" mapstructure:"pfcp,omitempty"`
}

type UPFUpdateStrategy struct {
	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}
