apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-exporter
  namespace: monarch
  labels:
    app: exporter
spec:
  selector:
    matchLabels:
      app: exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: exporter
    spec:
      containers:
        - image: ghcr.io/niloysh/rogers-workshop:v1.0
          name: exporter
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8000
          command: ["/bin/bash", "-c", "--"]
          # args: ["while true; do sleep 30000000; done;"]
          args: ["python -u exporter.py"]
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
      restartPolicy: Always