apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-configmap
  labels:
    app: open5gs
data:
  ausfcfg.yaml: |
    logger:
      file: /open5gs/install/var/log/open5gs/ausf.log

    global:
      max:
        ue: 1024

    ausf:
      sbi:
        server:
          - address: 0.0.0.0
            advertise: ausf-nausf
            port: 80
        client:
          scp:
            - uri: http://scp-nscp:80
