apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bsf-deployment.yaml
  - bsf-service.yaml

configMapGenerator:
  - name: bsf-configmap
    behavior: create
    files:
      - bsfcfg.yaml

generatorOptions:
  disableNameSuffixHash: true
