apiVersion: apps/v1
kind: Deployment
metadata:
  name: ueransim-ue101
  labels:
    app: ueransim
    component: ue
    name: ue101
spec:
  selector:
    matchLabels:
      app: ueransim
      component: ue
      name: ue101
  replicas: 1
  template:
    metadata:
      labels:
        app: ueransim
        component: ue
        name: ue101
    spec:
      containers:
        - image: ghcr.io/niloysh/ueransim:v3.2.6
          imagePullPolicy: Always
          name: ue
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command: ["/bin/bash", "-c", "--"]
          args:
            - |
              if [ "$DEBUG_MODE" = "true" ]; then
                while true; do sleep 30; done;
              else
                /ueransim/config/wrapper.sh
              fi
          env:
            - name: DEBUG_MODE
              value: "false"
          volumeMounts:
            - mountPath: /ueransim/config
              name: ue-volume
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: ue-volume
          configMap:
            name: ue101-configmap
            items:
              - key: ue.yaml
                path: ue.yaml
              - key: wrapper.sh
                path: wrapper.sh
                mode: 0755
