apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open5gs

resources:
  - amf
  - ausf
  - bsf
  - nrf
  - nssf
  - pcf
  - scp
  - smf1
  - udm
  - udr
  - upf1

images:
  - name: ghcr.io/niloysh/open5gs
    newTag: v2.7.0
