apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ausf-deployment.yaml
  - ausf-service.yaml

configMapGenerator:
  - name: ausf-configmap
    behavior: create
    files:
      - ausfcfg.yaml

generatorOptions:
  disableNameSuffixHash: true
