apiVersion: v1
kind: Service
metadata:
  name: pcf-npcf
  labels:
    app: open5gs
    nf: pcf
spec:
  ports:
    - name: sbi
      port: 80
    - name: metrics
      port: 9090
  selector:
    app: open5gs
    nf: pcf
