apiVersion: v1
kind: Service
metadata:
  name: monitoring-manager-service
  namespace: monarch
  labels:
    app: monarch
    component: monitoring-manager
spec:
  type: NodePort
  ports:
    - name: api # expose server port
      port: 6000 # which port is exposed
      targetPort: api # port name in pod
      nodePort: 30600
  selector:
    app: monarch # target pods
    component: monitoring-manager
