// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package render

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type AMF struct {
	// Affinity corresponds to the JSON schema field "affinity".
	Affinity map[string]interface{} `json:"affinity,omitempty" yaml:"affinity,omitempty" mapstructure:"affinity,omitempty"`

	// Args corresponds to the JSON schema field "args".
	Args []interface{} `json:"args,omitempty" yaml:"args,omitempty" mapstructure:"args,omitempty"`

	// Command corresponds to the JSON schema field "command".
	Command []interface{} `json:"command,omitempty" yaml:"command,omitempty" mapstructure:"command,omitempty"`

	// CommonAnnotations corresponds to the JSON schema field "commonAnnotations".
	CommonAnnotations map[string]interface{} `json:"commonAnnotations,omitempty" yaml:"commonAnnotations,omitempty" mapstructure:"commonAnnotations,omitempty"`

	// CommonLabels corresponds to the JSON schema field "commonLabels".
	CommonLabels map[string]interface{} `json:"commonLabels,omitempty" yaml:"commonLabels,omitempty" mapstructure:"commonLabels,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config *AMFConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// ContainerPorts corresponds to the JSON schema field "containerPorts".
	ContainerPorts *AMFContainerPorts `json:"containerPorts,omitempty" yaml:"containerPorts,omitempty" mapstructure:"containerPorts,omitempty"`

	// ContainerSecurityContext corresponds to the JSON schema field
	// "containerSecurityContext".
	ContainerSecurityContext *AMFContainerSecurityContext `json:"containerSecurityContext,omitempty" yaml:"containerSecurityContext,omitempty" mapstructure:"containerSecurityContext,omitempty"`

	// CustomLivenessProbe corresponds to the JSON schema field "customLivenessProbe".
	CustomLivenessProbe map[string]interface{} `json:"customLivenessProbe,omitempty" yaml:"customLivenessProbe,omitempty" mapstructure:"customLivenessProbe,omitempty"`

	// CustomOpen5GsConfig corresponds to the JSON schema field "customOpen5gsConfig".
	CustomOpen5GsConfig map[string]interface{} `json:"customOpen5gsConfig,omitempty" yaml:"customOpen5gsConfig,omitempty" mapstructure:"customOpen5gsConfig,omitempty"`

	// CustomReadinessProbe corresponds to the JSON schema field
	// "customReadinessProbe".
	CustomReadinessProbe map[string]interface{} `json:"customReadinessProbe,omitempty" yaml:"customReadinessProbe,omitempty" mapstructure:"customReadinessProbe,omitempty"`

	// CustomStartupProbe corresponds to the JSON schema field "customStartupProbe".
	CustomStartupProbe map[string]interface{} `json:"customStartupProbe,omitempty" yaml:"customStartupProbe,omitempty" mapstructure:"customStartupProbe,omitempty"`

	// ExtraDeploy corresponds to the JSON schema field "extraDeploy".
	ExtraDeploy []interface{} `json:"extraDeploy,omitempty" yaml:"extraDeploy,omitempty" mapstructure:"extraDeploy,omitempty"`

	// ExtraEnvVars corresponds to the JSON schema field "extraEnvVars".
	ExtraEnvVars []interface{} `json:"extraEnvVars,omitempty" yaml:"extraEnvVars,omitempty" mapstructure:"extraEnvVars,omitempty"`

	// ExtraEnvVarsCM corresponds to the JSON schema field "extraEnvVarsCM".
	ExtraEnvVarsCM *string `json:"extraEnvVarsCM,omitempty" yaml:"extraEnvVarsCM,omitempty" mapstructure:"extraEnvVarsCM,omitempty"`

	// ExtraEnvVarsSecret corresponds to the JSON schema field "extraEnvVarsSecret".
	ExtraEnvVarsSecret *string `json:"extraEnvVarsSecret,omitempty" yaml:"extraEnvVarsSecret,omitempty" mapstructure:"extraEnvVarsSecret,omitempty"`

	// ExtraVolumeMounts corresponds to the JSON schema field "extraVolumeMounts".
	ExtraVolumeMounts []interface{} `json:"extraVolumeMounts,omitempty" yaml:"extraVolumeMounts,omitempty" mapstructure:"extraVolumeMounts,omitempty"`

	// ExtraVolumes corresponds to the JSON schema field "extraVolumes".
	ExtraVolumes []interface{} `json:"extraVolumes,omitempty" yaml:"extraVolumes,omitempty" mapstructure:"extraVolumes,omitempty"`

	// FullnameOverride corresponds to the JSON schema field "fullnameOverride".
	FullnameOverride *string `json:"fullnameOverride,omitempty" yaml:"fullnameOverride,omitempty" mapstructure:"fullnameOverride,omitempty"`

	// Global corresponds to the JSON schema field "global".
	Global *AMFGlobal `json:"global,omitempty" yaml:"global,omitempty" mapstructure:"global,omitempty"`

	// HostAliases corresponds to the JSON schema field "hostAliases".
	HostAliases []interface{} `json:"hostAliases,omitempty" yaml:"hostAliases,omitempty" mapstructure:"hostAliases,omitempty"`

	// Image corresponds to the JSON schema field "image".
	Image *AMFImage `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// InitContainers corresponds to the JSON schema field "initContainers".
	InitContainers []interface{} `json:"initContainers,omitempty" yaml:"initContainers,omitempty" mapstructure:"initContainers,omitempty"`

	// KubeVersion corresponds to the JSON schema field "kubeVersion".
	KubeVersion *string `json:"kubeVersion,omitempty" yaml:"kubeVersion,omitempty" mapstructure:"kubeVersion,omitempty"`

	// LifecycleHooks corresponds to the JSON schema field "lifecycleHooks".
	LifecycleHooks map[string]interface{} `json:"lifecycleHooks,omitempty" yaml:"lifecycleHooks,omitempty" mapstructure:"lifecycleHooks,omitempty"`

	// LivenessProbe corresponds to the JSON schema field "livenessProbe".
	LivenessProbe *AMFLivenessProbe `json:"livenessProbe,omitempty" yaml:"livenessProbe,omitempty" mapstructure:"livenessProbe,omitempty"`

	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *AMFMetrics `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// NameOverride corresponds to the JSON schema field "nameOverride".
	NameOverride *string `json:"nameOverride,omitempty" yaml:"nameOverride,omitempty" mapstructure:"nameOverride,omitempty"`

	// NamespaceOverride corresponds to the JSON schema field "namespaceOverride".
	NamespaceOverride *string `json:"namespaceOverride,omitempty" yaml:"namespaceOverride,omitempty" mapstructure:"namespaceOverride,omitempty"`

	// NodeAffinityPreset corresponds to the JSON schema field "nodeAffinityPreset".
	NodeAffinityPreset *AMFNodeAffinityPreset `json:"nodeAffinityPreset,omitempty" yaml:"nodeAffinityPreset,omitempty" mapstructure:"nodeAffinityPreset,omitempty"`

	// NodeSelector corresponds to the JSON schema field "nodeSelector".
	NodeSelector map[string]interface{} `json:"nodeSelector,omitempty" yaml:"nodeSelector,omitempty" mapstructure:"nodeSelector,omitempty"`

	// PodAffinityPreset corresponds to the JSON schema field "podAffinityPreset".
	PodAffinityPreset *string `json:"podAffinityPreset,omitempty" yaml:"podAffinityPreset,omitempty" mapstructure:"podAffinityPreset,omitempty"`

	// PodAnnotations corresponds to the JSON schema field "podAnnotations".
	PodAnnotations map[string]interface{} `json:"podAnnotations,omitempty" yaml:"podAnnotations,omitempty" mapstructure:"podAnnotations,omitempty"`

	// PodAntiAffinityPreset corresponds to the JSON schema field
	// "podAntiAffinityPreset".
	PodAntiAffinityPreset *string `json:"podAntiAffinityPreset,omitempty" yaml:"podAntiAffinityPreset,omitempty" mapstructure:"podAntiAffinityPreset,omitempty"`

	// PodLabels corresponds to the JSON schema field "podLabels".
	PodLabels map[string]interface{} `json:"podLabels,omitempty" yaml:"podLabels,omitempty" mapstructure:"podLabels,omitempty"`

	// PodSecurityContext corresponds to the JSON schema field "podSecurityContext".
	PodSecurityContext *AMFPodSecurityContext `json:"podSecurityContext,omitempty" yaml:"podSecurityContext,omitempty" mapstructure:"podSecurityContext,omitempty"`

	// PriorityClassName corresponds to the JSON schema field "priorityClassName".
	PriorityClassName *string `json:"priorityClassName,omitempty" yaml:"priorityClassName,omitempty" mapstructure:"priorityClassName,omitempty"`

	// ReadinessProbe corresponds to the JSON schema field "readinessProbe".
	ReadinessProbe *AMFReadinessProbe `json:"readinessProbe,omitempty" yaml:"readinessProbe,omitempty" mapstructure:"readinessProbe,omitempty"`

	// ReplicaCount corresponds to the JSON schema field "replicaCount".
	ReplicaCount *int `json:"replicaCount,omitempty" yaml:"replicaCount,omitempty" mapstructure:"replicaCount,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *AMFResources `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// SchedulerName corresponds to the JSON schema field "schedulerName".
	SchedulerName *string `json:"schedulerName,omitempty" yaml:"schedulerName,omitempty" mapstructure:"schedulerName,omitempty"`

	// ServiceAccount corresponds to the JSON schema field "serviceAccount".
	ServiceAccount *AMFServiceAccount `json:"serviceAccount,omitempty" yaml:"serviceAccount,omitempty" mapstructure:"serviceAccount,omitempty"`

	// Services corresponds to the JSON schema field "services".
	Services *AMFServices `json:"services,omitempty" yaml:"services,omitempty" mapstructure:"services,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// Sidecars corresponds to the JSON schema field "sidecars".
	Sidecars []interface{} `json:"sidecars,omitempty" yaml:"sidecars,omitempty" mapstructure:"sidecars,omitempty"`

	// StartupProbe corresponds to the JSON schema field "startupProbe".
	StartupProbe *AMFStartupProbe `json:"startupProbe,omitempty" yaml:"startupProbe,omitempty" mapstructure:"startupProbe,omitempty"`

	// Tolerations corresponds to the JSON schema field "tolerations".
	Tolerations []interface{} `json:"tolerations,omitempty" yaml:"tolerations,omitempty" mapstructure:"tolerations,omitempty"`

	// TopologySpreadConstraints corresponds to the JSON schema field
	// "topologySpreadConstraints".
	TopologySpreadConstraints []interface{} `json:"topologySpreadConstraints,omitempty" yaml:"topologySpreadConstraints,omitempty" mapstructure:"topologySpreadConstraints,omitempty"`

	// UpdateStrategy corresponds to the JSON schema field "updateStrategy".
	UpdateStrategy *AMFUpdateStrategy `json:"updateStrategy,omitempty" yaml:"updateStrategy,omitempty" mapstructure:"updateStrategy,omitempty"`
}

type AMFConfig struct {
	// Advertise corresponds to the JSON schema field "advertise".
	Advertise *string `json:"advertise,omitempty" yaml:"advertise,omitempty" mapstructure:"advertise,omitempty"`

	// GuamiList corresponds to the JSON schema field "guamiList".
	GuamiList []AMFConfigGuamiListElem `json:"guamiList,omitempty" yaml:"guamiList,omitempty" mapstructure:"guamiList,omitempty"`

	// LogLevel corresponds to the JSON schema field "logLevel".
	LogLevel *string `json:"logLevel,omitempty" yaml:"logLevel,omitempty" mapstructure:"logLevel,omitempty"`

	// NetworkName corresponds to the JSON schema field "networkName".
	NetworkName *string `json:"networkName,omitempty" yaml:"networkName,omitempty" mapstructure:"networkName,omitempty"`

	// PlmnList corresponds to the JSON schema field "plmnList".
	PlmnList []AMFConfigPlmnListElem `json:"plmnList,omitempty" yaml:"plmnList,omitempty" mapstructure:"plmnList,omitempty"`

	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *AMFConfigSbi `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`

	// TaiList corresponds to the JSON schema field "taiList".
	TaiList []AMFConfigTaiListElem `json:"taiList,omitempty" yaml:"taiList,omitempty" mapstructure:"taiList,omitempty"`
}

type AMFConfigGuamiListElem struct {
	// AmfId corresponds to the JSON schema field "amf_id".
	AmfId *AMFConfigGuamiListElemAmfId `json:"amf_id,omitempty" yaml:"amf_id,omitempty" mapstructure:"amf_id,omitempty"`

	// PlmnId corresponds to the JSON schema field "plmn_id".
	PlmnId *AMFConfigGuamiListElemPlmnId `json:"plmn_id,omitempty" yaml:"plmn_id,omitempty" mapstructure:"plmn_id,omitempty"`
}

type AMFConfigGuamiListElemAmfId struct {
	// Region corresponds to the JSON schema field "region".
	Region *int `json:"region,omitempty" yaml:"region,omitempty" mapstructure:"region,omitempty"`

	// Set corresponds to the JSON schema field "set".
	Set *int `json:"set,omitempty" yaml:"set,omitempty" mapstructure:"set,omitempty"`
}

type AMFConfigGuamiListElemPlmnId struct {
	// Mcc corresponds to the JSON schema field "mcc".
	Mcc *string `json:"mcc,omitempty" yaml:"mcc,omitempty" mapstructure:"mcc,omitempty"`

	// Mnc corresponds to the JSON schema field "mnc".
	Mnc *string `json:"mnc,omitempty" yaml:"mnc,omitempty" mapstructure:"mnc,omitempty"`
}

type AMFConfigPlmnListElem struct {
	// PlmnId corresponds to the JSON schema field "plmn_id".
	PlmnId *AMFConfigPlmnListElemPlmnId `json:"plmn_id,omitempty" yaml:"plmn_id,omitempty" mapstructure:"plmn_id,omitempty"`

	// SNssai corresponds to the JSON schema field "s_nssai".
	SNssai []AMFConfigPlmnListElemSNssaiElem `json:"s_nssai,omitempty" yaml:"s_nssai,omitempty" mapstructure:"s_nssai,omitempty"`
}

type AMFConfigPlmnListElemPlmnId struct {
	// Mcc corresponds to the JSON schema field "mcc".
	Mcc *string `json:"mcc,omitempty" yaml:"mcc,omitempty" mapstructure:"mcc,omitempty"`

	// Mnc corresponds to the JSON schema field "mnc".
	Mnc *string `json:"mnc,omitempty" yaml:"mnc,omitempty" mapstructure:"mnc,omitempty"`
}

type AMFConfigPlmnListElemSNssaiElem struct {
	// Sd corresponds to the JSON schema field "sd".
	Sd *string `json:"sd,omitempty" yaml:"sd,omitempty" mapstructure:"sd,omitempty"`

	// Sst corresponds to the JSON schema field "sst".
	Sst *int `json:"sst,omitempty" yaml:"sst,omitempty" mapstructure:"sst,omitempty"`
}

type AMFConfigSbi struct {
	// Client corresponds to the JSON schema field "client".
	Client *AMFConfigSbiClient `json:"client,omitempty" yaml:"client,omitempty" mapstructure:"client,omitempty"`

	// Server corresponds to the JSON schema field "server".
	Server interface{} `json:"server,omitempty" yaml:"server,omitempty" mapstructure:"server,omitempty"`
}

type AMFConfigSbiClient struct {
	// Nrf corresponds to the JSON schema field "nrf".
	Nrf *AMFConfigSbiClientNrf `json:"nrf,omitempty" yaml:"nrf,omitempty" mapstructure:"nrf,omitempty"`

	// Scp corresponds to the JSON schema field "scp".
	Scp *AMFConfigSbiClientScp `json:"scp,omitempty" yaml:"scp,omitempty" mapstructure:"scp,omitempty"`
}

type AMFConfigSbiClientNrf struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri *string `json:"uri,omitempty" yaml:"uri,omitempty" mapstructure:"uri,omitempty"`
}

type AMFConfigSbiClientScp struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri *string `json:"uri,omitempty" yaml:"uri,omitempty" mapstructure:"uri,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AMFConfigSbi) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain AMFConfigSbi
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Server != nil {
		return fmt.Errorf("field %s: must be null", "server")
	}
	*j = AMFConfigSbi(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AMFConfigSbi) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type Plain AMFConfigSbi
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.Server != nil {
		return fmt.Errorf("field %s: must be null", "server")
	}
	*j = AMFConfigSbi(plain)
	return nil
}

type AMFConfigTaiListElem struct {
	// PlmnId corresponds to the JSON schema field "plmn_id".
	PlmnId *AMFConfigTaiListElemPlmnId `json:"plmn_id,omitempty" yaml:"plmn_id,omitempty" mapstructure:"plmn_id,omitempty"`

	// Tac corresponds to the JSON schema field "tac".
	Tac []int `json:"tac,omitempty" yaml:"tac,omitempty" mapstructure:"tac,omitempty"`
}

type AMFConfigTaiListElemPlmnId struct {
	// Mcc corresponds to the JSON schema field "mcc".
	Mcc *string `json:"mcc,omitempty" yaml:"mcc,omitempty" mapstructure:"mcc,omitempty"`

	// Mnc corresponds to the JSON schema field "mnc".
	Mnc *string `json:"mnc,omitempty" yaml:"mnc,omitempty" mapstructure:"mnc,omitempty"`
}

type AMFContainerPorts struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *int `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// Ngap corresponds to the JSON schema field "ngap".
	Ngap *int `json:"ngap,omitempty" yaml:"ngap,omitempty" mapstructure:"ngap,omitempty"`

	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *int `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type AMFContainerSecurityContext struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// RunAsNonRoot corresponds to the JSON schema field "runAsNonRoot".
	RunAsNonRoot *bool `json:"runAsNonRoot,omitempty" yaml:"runAsNonRoot,omitempty" mapstructure:"runAsNonRoot,omitempty"`

	// RunAsUser corresponds to the JSON schema field "runAsUser".
	RunAsUser *int `json:"runAsUser,omitempty" yaml:"runAsUser,omitempty" mapstructure:"runAsUser,omitempty"`
}

type AMFGlobal struct {
	// ImagePullSecrets corresponds to the JSON schema field "imagePullSecrets".
	ImagePullSecrets []interface{} `json:"imagePullSecrets,omitempty" yaml:"imagePullSecrets,omitempty" mapstructure:"imagePullSecrets,omitempty"`

	// ImageRegistry corresponds to the JSON schema field "imageRegistry".
	ImageRegistry *string `json:"imageRegistry,omitempty" yaml:"imageRegistry,omitempty" mapstructure:"imageRegistry,omitempty"`

	// StorageClass corresponds to the JSON schema field "storageClass".
	StorageClass *string `json:"storageClass,omitempty" yaml:"storageClass,omitempty" mapstructure:"storageClass,omitempty"`
}

type AMFImage struct {
	// Debug corresponds to the JSON schema field "debug".
	Debug *bool `json:"debug,omitempty" yaml:"debug,omitempty" mapstructure:"debug,omitempty"`

	// Digest corresponds to the JSON schema field "digest".
	Digest *string `json:"digest,omitempty" yaml:"digest,omitempty" mapstructure:"digest,omitempty"`

	// PullPolicy corresponds to the JSON schema field "pullPolicy".
	PullPolicy *string `json:"pullPolicy,omitempty" yaml:"pullPolicy,omitempty" mapstructure:"pullPolicy,omitempty"`

	// PullSecrets corresponds to the JSON schema field "pullSecrets".
	PullSecrets []interface{} `json:"pullSecrets,omitempty" yaml:"pullSecrets,omitempty" mapstructure:"pullSecrets,omitempty"`

	// Registry corresponds to the JSON schema field "registry".
	Registry *string `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository *string `json:"repository,omitempty" yaml:"repository,omitempty" mapstructure:"repository,omitempty"`

	// Tag corresponds to the JSON schema field "tag".
	Tag *string `json:"tag,omitempty" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`
}

type AMFLivenessProbe struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FailureThreshold corresponds to the JSON schema field "failureThreshold".
	FailureThreshold *int `json:"failureThreshold,omitempty" yaml:"failureThreshold,omitempty" mapstructure:"failureThreshold,omitempty"`

	// InitialDelaySeconds corresponds to the JSON schema field "initialDelaySeconds".
	InitialDelaySeconds *int `json:"initialDelaySeconds,omitempty" yaml:"initialDelaySeconds,omitempty" mapstructure:"initialDelaySeconds,omitempty"`

	// PeriodSeconds corresponds to the JSON schema field "periodSeconds".
	PeriodSeconds *int `json:"periodSeconds,omitempty" yaml:"periodSeconds,omitempty" mapstructure:"periodSeconds,omitempty"`

	// SuccessThreshold corresponds to the JSON schema field "successThreshold".
	SuccessThreshold *int `json:"successThreshold,omitempty" yaml:"successThreshold,omitempty" mapstructure:"successThreshold,omitempty"`

	// TimeoutSeconds corresponds to the JSON schema field "timeoutSeconds".
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty" yaml:"timeoutSeconds,omitempty" mapstructure:"timeoutSeconds,omitempty"`
}

type AMFMetrics struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// ServiceMonitor corresponds to the JSON schema field "serviceMonitor".
	ServiceMonitor *AMFMetricsServiceMonitor `json:"serviceMonitor,omitempty" yaml:"serviceMonitor,omitempty" mapstructure:"serviceMonitor,omitempty"`

	// ServiceScrape corresponds to the JSON schema field "serviceScrape".
	ServiceScrape *AMFMetricsServiceScrape `json:"serviceScrape,omitempty" yaml:"serviceScrape,omitempty" mapstructure:"serviceScrape,omitempty"`
}

type AMFMetricsServiceMonitor struct {
	// AdditionalLabels corresponds to the JSON schema field "additionalLabels".
	AdditionalLabels map[string]interface{} `json:"additionalLabels,omitempty" yaml:"additionalLabels,omitempty" mapstructure:"additionalLabels,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// HonorLabels corresponds to the JSON schema field "honorLabels".
	HonorLabels *bool `json:"honorLabels,omitempty" yaml:"honorLabels,omitempty" mapstructure:"honorLabels,omitempty"`

	// Interval corresponds to the JSON schema field "interval".
	Interval *string `json:"interval,omitempty" yaml:"interval,omitempty" mapstructure:"interval,omitempty"`

	// MetricRelabelings corresponds to the JSON schema field "metricRelabelings".
	MetricRelabelings []interface{} `json:"metricRelabelings,omitempty" yaml:"metricRelabelings,omitempty" mapstructure:"metricRelabelings,omitempty"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Relabelings corresponds to the JSON schema field "relabelings".
	Relabelings []interface{} `json:"relabelings,omitempty" yaml:"relabelings,omitempty" mapstructure:"relabelings,omitempty"`

	// ScrapeTimeout corresponds to the JSON schema field "scrapeTimeout".
	ScrapeTimeout *string `json:"scrapeTimeout,omitempty" yaml:"scrapeTimeout,omitempty" mapstructure:"scrapeTimeout,omitempty"`
}

type AMFMetricsServiceScrape struct {
	// AdditionalLabels corresponds to the JSON schema field "additionalLabels".
	AdditionalLabels map[string]interface{} `json:"additionalLabels,omitempty" yaml:"additionalLabels,omitempty" mapstructure:"additionalLabels,omitempty"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Namespace corresponds to the JSON schema field "namespace".
	Namespace *string `json:"namespace,omitempty" yaml:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// ScrapeInterval corresponds to the JSON schema field "scrape_interval".
	ScrapeInterval *string `json:"scrape_interval,omitempty" yaml:"scrape_interval,omitempty" mapstructure:"scrape_interval,omitempty"`
}

type AMFNodeAffinityPreset struct {
	// Key corresponds to the JSON schema field "key".
	Key *string `json:"key,omitempty" yaml:"key,omitempty" mapstructure:"key,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// Values corresponds to the JSON schema field "values".
	Values []interface{} `json:"values,omitempty" yaml:"values,omitempty" mapstructure:"values,omitempty"`
}

type AMFPodSecurityContext struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FsGroup corresponds to the JSON schema field "fsGroup".
	FsGroup *int `json:"fsGroup,omitempty" yaml:"fsGroup,omitempty" mapstructure:"fsGroup,omitempty"`
}

type AMFReadinessProbe struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FailureThreshold corresponds to the JSON schema field "failureThreshold".
	FailureThreshold *int `json:"failureThreshold,omitempty" yaml:"failureThreshold,omitempty" mapstructure:"failureThreshold,omitempty"`

	// InitialDelaySeconds corresponds to the JSON schema field "initialDelaySeconds".
	InitialDelaySeconds *int `json:"initialDelaySeconds,omitempty" yaml:"initialDelaySeconds,omitempty" mapstructure:"initialDelaySeconds,omitempty"`

	// PeriodSeconds corresponds to the JSON schema field "periodSeconds".
	PeriodSeconds *int `json:"periodSeconds,omitempty" yaml:"periodSeconds,omitempty" mapstructure:"periodSeconds,omitempty"`

	// SuccessThreshold corresponds to the JSON schema field "successThreshold".
	SuccessThreshold *int `json:"successThreshold,omitempty" yaml:"successThreshold,omitempty" mapstructure:"successThreshold,omitempty"`

	// TimeoutSeconds corresponds to the JSON schema field "timeoutSeconds".
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty" yaml:"timeoutSeconds,omitempty" mapstructure:"timeoutSeconds,omitempty"`
}

type AMFResources struct {
	// Limits corresponds to the JSON schema field "limits".
	Limits map[string]interface{} `json:"limits,omitempty" yaml:"limits,omitempty" mapstructure:"limits,omitempty"`

	// Requests corresponds to the JSON schema field "requests".
	Requests map[string]interface{} `json:"requests,omitempty" yaml:"requests,omitempty" mapstructure:"requests,omitempty"`
}

type AMFServiceAccount struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations map[string]interface{} `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// AutomountServiceAccountToken corresponds to the JSON schema field
	// "automountServiceAccountToken".
	AutomountServiceAccountToken *bool `json:"automountServiceAccountToken,omitempty" yaml:"automountServiceAccountToken,omitempty" mapstructure:"automountServiceAccountToken,omitempty"`

	// Create corresponds to the JSON schema field "create".
	Create *bool `json:"create,omitempty" yaml:"create,omitempty" mapstructure:"create,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type AMFServices struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *AMFServicesMetrics `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`

	// Ngap corresponds to the JSON schema field "ngap".
	Ngap *AMFServicesNgap `json:"ngap,omitempty" yaml:"ngap,omitempty" mapstructure:"ngap,omitempty"`

	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *AMFServicesSbi `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type AMFServicesMetrics struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations *AMFServicesMetricsAnnotations `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// ClusterIP corresponds to the JSON schema field "clusterIP".
	ClusterIP *string `json:"clusterIP,omitempty" yaml:"clusterIP,omitempty" mapstructure:"clusterIP,omitempty"`

	// ExternalTrafficPolicy corresponds to the JSON schema field
	// "externalTrafficPolicy".
	ExternalTrafficPolicy *string `json:"externalTrafficPolicy,omitempty" yaml:"externalTrafficPolicy,omitempty" mapstructure:"externalTrafficPolicy,omitempty"`

	// ExtraPorts corresponds to the JSON schema field "extraPorts".
	ExtraPorts []interface{} `json:"extraPorts,omitempty" yaml:"extraPorts,omitempty" mapstructure:"extraPorts,omitempty"`

	// LoadBalancerIP corresponds to the JSON schema field "loadBalancerIP".
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty" yaml:"loadBalancerIP,omitempty" mapstructure:"loadBalancerIP,omitempty"`

	// LoadBalancerSourceRanges corresponds to the JSON schema field
	// "loadBalancerSourceRanges".
	LoadBalancerSourceRanges []interface{} `json:"loadBalancerSourceRanges,omitempty" yaml:"loadBalancerSourceRanges,omitempty" mapstructure:"loadBalancerSourceRanges,omitempty"`

	// NodePorts corresponds to the JSON schema field "nodePorts".
	NodePorts *AMFServicesMetricsNodePorts `json:"nodePorts,omitempty" yaml:"nodePorts,omitempty" mapstructure:"nodePorts,omitempty"`

	// Ports corresponds to the JSON schema field "ports".
	Ports *AMFServicesMetricsPorts `json:"ports,omitempty" yaml:"ports,omitempty" mapstructure:"ports,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// SessionAffinityConfig corresponds to the JSON schema field
	// "sessionAffinityConfig".
	SessionAffinityConfig map[string]interface{} `json:"sessionAffinityConfig,omitempty" yaml:"sessionAffinityConfig,omitempty" mapstructure:"sessionAffinityConfig,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type AMFServicesMetricsAnnotations struct {
	// PrometheusIoPath corresponds to the JSON schema field "prometheus.io/path".
	PrometheusIoPath *string `json:"prometheus.io/path,omitempty" yaml:"prometheus.io/path,omitempty" mapstructure:"prometheus.io/path,omitempty"`
}

type AMFServicesMetricsNodePorts struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *string `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`
}

type AMFServicesMetricsPorts struct {
	// Metrics corresponds to the JSON schema field "metrics".
	Metrics *int `json:"metrics,omitempty" yaml:"metrics,omitempty" mapstructure:"metrics,omitempty"`
}

type AMFServicesNgap struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations map[string]interface{} `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// ClusterIP corresponds to the JSON schema field "clusterIP".
	ClusterIP *string `json:"clusterIP,omitempty" yaml:"clusterIP,omitempty" mapstructure:"clusterIP,omitempty"`

	// ExternalTrafficPolicy corresponds to the JSON schema field
	// "externalTrafficPolicy".
	ExternalTrafficPolicy *string `json:"externalTrafficPolicy,omitempty" yaml:"externalTrafficPolicy,omitempty" mapstructure:"externalTrafficPolicy,omitempty"`

	// ExtraPorts corresponds to the JSON schema field "extraPorts".
	ExtraPorts []interface{} `json:"extraPorts,omitempty" yaml:"extraPorts,omitempty" mapstructure:"extraPorts,omitempty"`

	// LoadBalancerIP corresponds to the JSON schema field "loadBalancerIP".
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty" yaml:"loadBalancerIP,omitempty" mapstructure:"loadBalancerIP,omitempty"`

	// LoadBalancerSourceRanges corresponds to the JSON schema field
	// "loadBalancerSourceRanges".
	LoadBalancerSourceRanges []interface{} `json:"loadBalancerSourceRanges,omitempty" yaml:"loadBalancerSourceRanges,omitempty" mapstructure:"loadBalancerSourceRanges,omitempty"`

	// NodePorts corresponds to the JSON schema field "nodePorts".
	NodePorts *AMFServicesNgapNodePorts `json:"nodePorts,omitempty" yaml:"nodePorts,omitempty" mapstructure:"nodePorts,omitempty"`

	// Ports corresponds to the JSON schema field "ports".
	Ports *AMFServicesNgapPorts `json:"ports,omitempty" yaml:"ports,omitempty" mapstructure:"ports,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// SessionAffinityConfig corresponds to the JSON schema field
	// "sessionAffinityConfig".
	SessionAffinityConfig map[string]interface{} `json:"sessionAffinityConfig,omitempty" yaml:"sessionAffinityConfig,omitempty" mapstructure:"sessionAffinityConfig,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type AMFServicesNgapNodePorts struct {
	// Ngap corresponds to the JSON schema field "ngap".
	Ngap *string `json:"ngap,omitempty" yaml:"ngap,omitempty" mapstructure:"ngap,omitempty"`
}

type AMFServicesNgapPorts struct {
	// Ngap corresponds to the JSON schema field "ngap".
	Ngap *int `json:"ngap,omitempty" yaml:"ngap,omitempty" mapstructure:"ngap,omitempty"`
}

type AMFServicesSbi struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations map[string]interface{} `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// ClusterIP corresponds to the JSON schema field "clusterIP".
	ClusterIP *string `json:"clusterIP,omitempty" yaml:"clusterIP,omitempty" mapstructure:"clusterIP,omitempty"`

	// ExternalTrafficPolicy corresponds to the JSON schema field
	// "externalTrafficPolicy".
	ExternalTrafficPolicy *string `json:"externalTrafficPolicy,omitempty" yaml:"externalTrafficPolicy,omitempty" mapstructure:"externalTrafficPolicy,omitempty"`

	// ExtraPorts corresponds to the JSON schema field "extraPorts".
	ExtraPorts []interface{} `json:"extraPorts,omitempty" yaml:"extraPorts,omitempty" mapstructure:"extraPorts,omitempty"`

	// LoadBalancerIP corresponds to the JSON schema field "loadBalancerIP".
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty" yaml:"loadBalancerIP,omitempty" mapstructure:"loadBalancerIP,omitempty"`

	// LoadBalancerSourceRanges corresponds to the JSON schema field
	// "loadBalancerSourceRanges".
	LoadBalancerSourceRanges []interface{} `json:"loadBalancerSourceRanges,omitempty" yaml:"loadBalancerSourceRanges,omitempty" mapstructure:"loadBalancerSourceRanges,omitempty"`

	// NodePorts corresponds to the JSON schema field "nodePorts".
	NodePorts *AMFServicesSbiNodePorts `json:"nodePorts,omitempty" yaml:"nodePorts,omitempty" mapstructure:"nodePorts,omitempty"`

	// Ports corresponds to the JSON schema field "ports".
	Ports *AMFServicesSbiPorts `json:"ports,omitempty" yaml:"ports,omitempty" mapstructure:"ports,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// SessionAffinityConfig corresponds to the JSON schema field
	// "sessionAffinityConfig".
	SessionAffinityConfig map[string]interface{} `json:"sessionAffinityConfig,omitempty" yaml:"sessionAffinityConfig,omitempty" mapstructure:"sessionAffinityConfig,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type AMFServicesSbiNodePorts struct {
	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *string `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type AMFServicesSbiPorts struct {
	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *int `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type AMFStartupProbe struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FailureThreshold corresponds to the JSON schema field "failureThreshold".
	FailureThreshold *int `json:"failureThreshold,omitempty" yaml:"failureThreshold,omitempty" mapstructure:"failureThreshold,omitempty"`

	// InitialDelaySeconds corresponds to the JSON schema field "initialDelaySeconds".
	InitialDelaySeconds *int `json:"initialDelaySeconds,omitempty" yaml:"initialDelaySeconds,omitempty" mapstructure:"initialDelaySeconds,omitempty"`

	// Path corresponds to the JSON schema field "path".
	Path *string `json:"path,omitempty" yaml:"path,omitempty" mapstructure:"path,omitempty"`

	// PeriodSeconds corresponds to the JSON schema field "periodSeconds".
	PeriodSeconds *int `json:"periodSeconds,omitempty" yaml:"periodSeconds,omitempty" mapstructure:"periodSeconds,omitempty"`

	// SuccessThreshold corresponds to the JSON schema field "successThreshold".
	SuccessThreshold *int `json:"successThreshold,omitempty" yaml:"successThreshold,omitempty" mapstructure:"successThreshold,omitempty"`

	// TimeoutSeconds corresponds to the JSON schema field "timeoutSeconds".
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty" yaml:"timeoutSeconds,omitempty" mapstructure:"timeoutSeconds,omitempty"`
}

type AMFUpdateStrategy struct {
	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}
