// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package render

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type UDM struct {
	// Affinity corresponds to the JSON schema field "affinity".
	Affinity map[string]interface{} `json:"affinity,omitempty" yaml:"affinity,omitempty" mapstructure:"affinity,omitempty"`

	// Args corresponds to the JSON schema field "args".
	Args []interface{} `json:"args,omitempty" yaml:"args,omitempty" mapstructure:"args,omitempty"`

	// Command corresponds to the JSON schema field "command".
	Command []interface{} `json:"command,omitempty" yaml:"command,omitempty" mapstructure:"command,omitempty"`

	// CommonAnnotations corresponds to the JSON schema field "commonAnnotations".
	CommonAnnotations map[string]interface{} `json:"commonAnnotations,omitempty" yaml:"commonAnnotations,omitempty" mapstructure:"commonAnnotations,omitempty"`

	// CommonLabels corresponds to the JSON schema field "commonLabels".
	CommonLabels map[string]interface{} `json:"commonLabels,omitempty" yaml:"commonLabels,omitempty" mapstructure:"commonLabels,omitempty"`

	// Config corresponds to the JSON schema field "config".
	Config *UDMConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// ContainerPorts corresponds to the JSON schema field "containerPorts".
	ContainerPorts *UDMContainerPorts `json:"containerPorts,omitempty" yaml:"containerPorts,omitempty" mapstructure:"containerPorts,omitempty"`

	// ContainerSecurityContext corresponds to the JSON schema field
	// "containerSecurityContext".
	ContainerSecurityContext *UDMContainerSecurityContext `json:"containerSecurityContext,omitempty" yaml:"containerSecurityContext,omitempty" mapstructure:"containerSecurityContext,omitempty"`

	// CustomLivenessProbe corresponds to the JSON schema field "customLivenessProbe".
	CustomLivenessProbe map[string]interface{} `json:"customLivenessProbe,omitempty" yaml:"customLivenessProbe,omitempty" mapstructure:"customLivenessProbe,omitempty"`

	// CustomOpen5GsConfig corresponds to the JSON schema field "customOpen5gsConfig".
	CustomOpen5GsConfig map[string]interface{} `json:"customOpen5gsConfig,omitempty" yaml:"customOpen5gsConfig,omitempty" mapstructure:"customOpen5gsConfig,omitempty"`

	// CustomReadinessProbe corresponds to the JSON schema field
	// "customReadinessProbe".
	CustomReadinessProbe map[string]interface{} `json:"customReadinessProbe,omitempty" yaml:"customReadinessProbe,omitempty" mapstructure:"customReadinessProbe,omitempty"`

	// CustomStartupProbe corresponds to the JSON schema field "customStartupProbe".
	CustomStartupProbe map[string]interface{} `json:"customStartupProbe,omitempty" yaml:"customStartupProbe,omitempty" mapstructure:"customStartupProbe,omitempty"`

	// ExtraDeploy corresponds to the JSON schema field "extraDeploy".
	ExtraDeploy []interface{} `json:"extraDeploy,omitempty" yaml:"extraDeploy,omitempty" mapstructure:"extraDeploy,omitempty"`

	// ExtraEnvVars corresponds to the JSON schema field "extraEnvVars".
	ExtraEnvVars []interface{} `json:"extraEnvVars,omitempty" yaml:"extraEnvVars,omitempty" mapstructure:"extraEnvVars,omitempty"`

	// ExtraEnvVarsCM corresponds to the JSON schema field "extraEnvVarsCM".
	ExtraEnvVarsCM *string `json:"extraEnvVarsCM,omitempty" yaml:"extraEnvVarsCM,omitempty" mapstructure:"extraEnvVarsCM,omitempty"`

	// ExtraEnvVarsSecret corresponds to the JSON schema field "extraEnvVarsSecret".
	ExtraEnvVarsSecret *string `json:"extraEnvVarsSecret,omitempty" yaml:"extraEnvVarsSecret,omitempty" mapstructure:"extraEnvVarsSecret,omitempty"`

	// ExtraVolumeMounts corresponds to the JSON schema field "extraVolumeMounts".
	ExtraVolumeMounts []interface{} `json:"extraVolumeMounts,omitempty" yaml:"extraVolumeMounts,omitempty" mapstructure:"extraVolumeMounts,omitempty"`

	// ExtraVolumes corresponds to the JSON schema field "extraVolumes".
	ExtraVolumes []interface{} `json:"extraVolumes,omitempty" yaml:"extraVolumes,omitempty" mapstructure:"extraVolumes,omitempty"`

	// FullnameOverride corresponds to the JSON schema field "fullnameOverride".
	FullnameOverride *string `json:"fullnameOverride,omitempty" yaml:"fullnameOverride,omitempty" mapstructure:"fullnameOverride,omitempty"`

	// Global corresponds to the JSON schema field "global".
	Global *UDMGlobal `json:"global,omitempty" yaml:"global,omitempty" mapstructure:"global,omitempty"`

	// HostAliases corresponds to the JSON schema field "hostAliases".
	HostAliases []interface{} `json:"hostAliases,omitempty" yaml:"hostAliases,omitempty" mapstructure:"hostAliases,omitempty"`

	// Image corresponds to the JSON schema field "image".
	Image *UDMImage `json:"image,omitempty" yaml:"image,omitempty" mapstructure:"image,omitempty"`

	// InitContainers corresponds to the JSON schema field "initContainers".
	InitContainers []interface{} `json:"initContainers,omitempty" yaml:"initContainers,omitempty" mapstructure:"initContainers,omitempty"`

	// KubeVersion corresponds to the JSON schema field "kubeVersion".
	KubeVersion *string `json:"kubeVersion,omitempty" yaml:"kubeVersion,omitempty" mapstructure:"kubeVersion,omitempty"`

	// LifecycleHooks corresponds to the JSON schema field "lifecycleHooks".
	LifecycleHooks map[string]interface{} `json:"lifecycleHooks,omitempty" yaml:"lifecycleHooks,omitempty" mapstructure:"lifecycleHooks,omitempty"`

	// LivenessProbe corresponds to the JSON schema field "livenessProbe".
	LivenessProbe *UDMLivenessProbe `json:"livenessProbe,omitempty" yaml:"livenessProbe,omitempty" mapstructure:"livenessProbe,omitempty"`

	// NameOverride corresponds to the JSON schema field "nameOverride".
	NameOverride *string `json:"nameOverride,omitempty" yaml:"nameOverride,omitempty" mapstructure:"nameOverride,omitempty"`

	// NamespaceOverride corresponds to the JSON schema field "namespaceOverride".
	NamespaceOverride *string `json:"namespaceOverride,omitempty" yaml:"namespaceOverride,omitempty" mapstructure:"namespaceOverride,omitempty"`

	// NodeAffinityPreset corresponds to the JSON schema field "nodeAffinityPreset".
	NodeAffinityPreset *UDMNodeAffinityPreset `json:"nodeAffinityPreset,omitempty" yaml:"nodeAffinityPreset,omitempty" mapstructure:"nodeAffinityPreset,omitempty"`

	// NodeSelector corresponds to the JSON schema field "nodeSelector".
	NodeSelector map[string]interface{} `json:"nodeSelector,omitempty" yaml:"nodeSelector,omitempty" mapstructure:"nodeSelector,omitempty"`

	// PodAffinityPreset corresponds to the JSON schema field "podAffinityPreset".
	PodAffinityPreset *string `json:"podAffinityPreset,omitempty" yaml:"podAffinityPreset,omitempty" mapstructure:"podAffinityPreset,omitempty"`

	// PodAnnotations corresponds to the JSON schema field "podAnnotations".
	PodAnnotations map[string]interface{} `json:"podAnnotations,omitempty" yaml:"podAnnotations,omitempty" mapstructure:"podAnnotations,omitempty"`

	// PodAntiAffinityPreset corresponds to the JSON schema field
	// "podAntiAffinityPreset".
	PodAntiAffinityPreset *string `json:"podAntiAffinityPreset,omitempty" yaml:"podAntiAffinityPreset,omitempty" mapstructure:"podAntiAffinityPreset,omitempty"`

	// PodLabels corresponds to the JSON schema field "podLabels".
	PodLabels map[string]interface{} `json:"podLabels,omitempty" yaml:"podLabels,omitempty" mapstructure:"podLabels,omitempty"`

	// PodSecurityContext corresponds to the JSON schema field "podSecurityContext".
	PodSecurityContext *UDMPodSecurityContext `json:"podSecurityContext,omitempty" yaml:"podSecurityContext,omitempty" mapstructure:"podSecurityContext,omitempty"`

	// PriorityClassName corresponds to the JSON schema field "priorityClassName".
	PriorityClassName *string `json:"priorityClassName,omitempty" yaml:"priorityClassName,omitempty" mapstructure:"priorityClassName,omitempty"`

	// ReadinessProbe corresponds to the JSON schema field "readinessProbe".
	ReadinessProbe *UDMReadinessProbe `json:"readinessProbe,omitempty" yaml:"readinessProbe,omitempty" mapstructure:"readinessProbe,omitempty"`

	// ReplicaCount corresponds to the JSON schema field "replicaCount".
	ReplicaCount *int `json:"replicaCount,omitempty" yaml:"replicaCount,omitempty" mapstructure:"replicaCount,omitempty"`

	// Resources corresponds to the JSON schema field "resources".
	Resources *UDMResources `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// SchedulerName corresponds to the JSON schema field "schedulerName".
	SchedulerName *string `json:"schedulerName,omitempty" yaml:"schedulerName,omitempty" mapstructure:"schedulerName,omitempty"`

	// ServiceAccount corresponds to the JSON schema field "serviceAccount".
	ServiceAccount *UDMServiceAccount `json:"serviceAccount,omitempty" yaml:"serviceAccount,omitempty" mapstructure:"serviceAccount,omitempty"`

	// Services corresponds to the JSON schema field "services".
	Services *UDMServices `json:"services,omitempty" yaml:"services,omitempty" mapstructure:"services,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// Sidecars corresponds to the JSON schema field "sidecars".
	Sidecars []interface{} `json:"sidecars,omitempty" yaml:"sidecars,omitempty" mapstructure:"sidecars,omitempty"`

	// StartupProbe corresponds to the JSON schema field "startupProbe".
	StartupProbe *UDMStartupProbe `json:"startupProbe,omitempty" yaml:"startupProbe,omitempty" mapstructure:"startupProbe,omitempty"`

	// Tolerations corresponds to the JSON schema field "tolerations".
	Tolerations []interface{} `json:"tolerations,omitempty" yaml:"tolerations,omitempty" mapstructure:"tolerations,omitempty"`

	// TopologySpreadConstraints corresponds to the JSON schema field
	// "topologySpreadConstraints".
	TopologySpreadConstraints []interface{} `json:"topologySpreadConstraints,omitempty" yaml:"topologySpreadConstraints,omitempty" mapstructure:"topologySpreadConstraints,omitempty"`

	// UpdateStrategy corresponds to the JSON schema field "updateStrategy".
	UpdateStrategy *UDMUpdateStrategy `json:"updateStrategy,omitempty" yaml:"updateStrategy,omitempty" mapstructure:"updateStrategy,omitempty"`
}

type UDMConfig struct {
	// Advertise corresponds to the JSON schema field "advertise".
	Advertise *string `json:"advertise,omitempty" yaml:"advertise,omitempty" mapstructure:"advertise,omitempty"`

	// LogLevel corresponds to the JSON schema field "logLevel".
	LogLevel *string `json:"logLevel,omitempty" yaml:"logLevel,omitempty" mapstructure:"logLevel,omitempty"`

	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *UDMConfigSbi `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type UDMConfigSbi struct {
	// Client corresponds to the JSON schema field "client".
	Client *UDMConfigSbiClient `json:"client,omitempty" yaml:"client,omitempty" mapstructure:"client,omitempty"`

	// Server corresponds to the JSON schema field "server".
	Server interface{} `json:"server,omitempty" yaml:"server,omitempty" mapstructure:"server,omitempty"`
}

type UDMConfigSbiClient struct {
	// Nrf corresponds to the JSON schema field "nrf".
	Nrf *UDMConfigSbiClientNrf `json:"nrf,omitempty" yaml:"nrf,omitempty" mapstructure:"nrf,omitempty"`

	// Scp corresponds to the JSON schema field "scp".
	Scp *UDMConfigSbiClientScp `json:"scp,omitempty" yaml:"scp,omitempty" mapstructure:"scp,omitempty"`
}

type UDMConfigSbiClientNrf struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri *string `json:"uri,omitempty" yaml:"uri,omitempty" mapstructure:"uri,omitempty"`
}

type UDMConfigSbiClientScp struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri *string `json:"uri,omitempty" yaml:"uri,omitempty" mapstructure:"uri,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UDMConfigSbi) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain UDMConfigSbi
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Server != nil {
		return fmt.Errorf("field %s: must be null", "server")
	}
	*j = UDMConfigSbi(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *UDMConfigSbi) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	type Plain UDMConfigSbi
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	if plain.Server != nil {
		return fmt.Errorf("field %s: must be null", "server")
	}
	*j = UDMConfigSbi(plain)
	return nil
}

type UDMContainerPorts struct {
	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *int `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type UDMContainerSecurityContext struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// RunAsNonRoot corresponds to the JSON schema field "runAsNonRoot".
	RunAsNonRoot *bool `json:"runAsNonRoot,omitempty" yaml:"runAsNonRoot,omitempty" mapstructure:"runAsNonRoot,omitempty"`

	// RunAsUser corresponds to the JSON schema field "runAsUser".
	RunAsUser *int `json:"runAsUser,omitempty" yaml:"runAsUser,omitempty" mapstructure:"runAsUser,omitempty"`
}

type UDMGlobal struct {
	// ImagePullSecrets corresponds to the JSON schema field "imagePullSecrets".
	ImagePullSecrets []interface{} `json:"imagePullSecrets,omitempty" yaml:"imagePullSecrets,omitempty" mapstructure:"imagePullSecrets,omitempty"`

	// ImageRegistry corresponds to the JSON schema field "imageRegistry".
	ImageRegistry *string `json:"imageRegistry,omitempty" yaml:"imageRegistry,omitempty" mapstructure:"imageRegistry,omitempty"`

	// StorageClass corresponds to the JSON schema field "storageClass".
	StorageClass *string `json:"storageClass,omitempty" yaml:"storageClass,omitempty" mapstructure:"storageClass,omitempty"`
}

type UDMImage struct {
	// Debug corresponds to the JSON schema field "debug".
	Debug *bool `json:"debug,omitempty" yaml:"debug,omitempty" mapstructure:"debug,omitempty"`

	// Digest corresponds to the JSON schema field "digest".
	Digest *string `json:"digest,omitempty" yaml:"digest,omitempty" mapstructure:"digest,omitempty"`

	// PullPolicy corresponds to the JSON schema field "pullPolicy".
	PullPolicy *string `json:"pullPolicy,omitempty" yaml:"pullPolicy,omitempty" mapstructure:"pullPolicy,omitempty"`

	// PullSecrets corresponds to the JSON schema field "pullSecrets".
	PullSecrets []interface{} `json:"pullSecrets,omitempty" yaml:"pullSecrets,omitempty" mapstructure:"pullSecrets,omitempty"`

	// Registry corresponds to the JSON schema field "registry".
	Registry *string `json:"registry,omitempty" yaml:"registry,omitempty" mapstructure:"registry,omitempty"`

	// Repository corresponds to the JSON schema field "repository".
	Repository *string `json:"repository,omitempty" yaml:"repository,omitempty" mapstructure:"repository,omitempty"`

	// Tag corresponds to the JSON schema field "tag".
	Tag *string `json:"tag,omitempty" yaml:"tag,omitempty" mapstructure:"tag,omitempty"`
}

type UDMLivenessProbe struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FailureThreshold corresponds to the JSON schema field "failureThreshold".
	FailureThreshold *int `json:"failureThreshold,omitempty" yaml:"failureThreshold,omitempty" mapstructure:"failureThreshold,omitempty"`

	// InitialDelaySeconds corresponds to the JSON schema field "initialDelaySeconds".
	InitialDelaySeconds *int `json:"initialDelaySeconds,omitempty" yaml:"initialDelaySeconds,omitempty" mapstructure:"initialDelaySeconds,omitempty"`

	// PeriodSeconds corresponds to the JSON schema field "periodSeconds".
	PeriodSeconds *int `json:"periodSeconds,omitempty" yaml:"periodSeconds,omitempty" mapstructure:"periodSeconds,omitempty"`

	// SuccessThreshold corresponds to the JSON schema field "successThreshold".
	SuccessThreshold *int `json:"successThreshold,omitempty" yaml:"successThreshold,omitempty" mapstructure:"successThreshold,omitempty"`

	// TimeoutSeconds corresponds to the JSON schema field "timeoutSeconds".
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty" yaml:"timeoutSeconds,omitempty" mapstructure:"timeoutSeconds,omitempty"`
}

type UDMNodeAffinityPreset struct {
	// Key corresponds to the JSON schema field "key".
	Key *string `json:"key,omitempty" yaml:"key,omitempty" mapstructure:"key,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// Values corresponds to the JSON schema field "values".
	Values []interface{} `json:"values,omitempty" yaml:"values,omitempty" mapstructure:"values,omitempty"`
}

type UDMPodSecurityContext struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FsGroup corresponds to the JSON schema field "fsGroup".
	FsGroup *int `json:"fsGroup,omitempty" yaml:"fsGroup,omitempty" mapstructure:"fsGroup,omitempty"`
}

type UDMReadinessProbe struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FailureThreshold corresponds to the JSON schema field "failureThreshold".
	FailureThreshold *int `json:"failureThreshold,omitempty" yaml:"failureThreshold,omitempty" mapstructure:"failureThreshold,omitempty"`

	// InitialDelaySeconds corresponds to the JSON schema field "initialDelaySeconds".
	InitialDelaySeconds *int `json:"initialDelaySeconds,omitempty" yaml:"initialDelaySeconds,omitempty" mapstructure:"initialDelaySeconds,omitempty"`

	// PeriodSeconds corresponds to the JSON schema field "periodSeconds".
	PeriodSeconds *int `json:"periodSeconds,omitempty" yaml:"periodSeconds,omitempty" mapstructure:"periodSeconds,omitempty"`

	// SuccessThreshold corresponds to the JSON schema field "successThreshold".
	SuccessThreshold *int `json:"successThreshold,omitempty" yaml:"successThreshold,omitempty" mapstructure:"successThreshold,omitempty"`

	// TimeoutSeconds corresponds to the JSON schema field "timeoutSeconds".
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty" yaml:"timeoutSeconds,omitempty" mapstructure:"timeoutSeconds,omitempty"`
}

type UDMResources struct {
	// Limits corresponds to the JSON schema field "limits".
	Limits map[string]interface{} `json:"limits,omitempty" yaml:"limits,omitempty" mapstructure:"limits,omitempty"`

	// Requests corresponds to the JSON schema field "requests".
	Requests map[string]interface{} `json:"requests,omitempty" yaml:"requests,omitempty" mapstructure:"requests,omitempty"`
}

type UDMServiceAccount struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations map[string]interface{} `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// AutomountServiceAccountToken corresponds to the JSON schema field
	// "automountServiceAccountToken".
	AutomountServiceAccountToken *bool `json:"automountServiceAccountToken,omitempty" yaml:"automountServiceAccountToken,omitempty" mapstructure:"automountServiceAccountToken,omitempty"`

	// Create corresponds to the JSON schema field "create".
	Create *bool `json:"create,omitempty" yaml:"create,omitempty" mapstructure:"create,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty" yaml:"name,omitempty" mapstructure:"name,omitempty"`
}

type UDMServices struct {
	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *UDMServicesSbi `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type UDMServicesSbi struct {
	// Annotations corresponds to the JSON schema field "annotations".
	Annotations map[string]interface{} `json:"annotations,omitempty" yaml:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// ClusterIP corresponds to the JSON schema field "clusterIP".
	ClusterIP *string `json:"clusterIP,omitempty" yaml:"clusterIP,omitempty" mapstructure:"clusterIP,omitempty"`

	// ExternalTrafficPolicy corresponds to the JSON schema field
	// "externalTrafficPolicy".
	ExternalTrafficPolicy *string `json:"externalTrafficPolicy,omitempty" yaml:"externalTrafficPolicy,omitempty" mapstructure:"externalTrafficPolicy,omitempty"`

	// ExtraPorts corresponds to the JSON schema field "extraPorts".
	ExtraPorts []interface{} `json:"extraPorts,omitempty" yaml:"extraPorts,omitempty" mapstructure:"extraPorts,omitempty"`

	// LoadBalancerIP corresponds to the JSON schema field "loadBalancerIP".
	LoadBalancerIP *string `json:"loadBalancerIP,omitempty" yaml:"loadBalancerIP,omitempty" mapstructure:"loadBalancerIP,omitempty"`

	// LoadBalancerSourceRanges corresponds to the JSON schema field
	// "loadBalancerSourceRanges".
	LoadBalancerSourceRanges []interface{} `json:"loadBalancerSourceRanges,omitempty" yaml:"loadBalancerSourceRanges,omitempty" mapstructure:"loadBalancerSourceRanges,omitempty"`

	// NodePorts corresponds to the JSON schema field "nodePorts".
	NodePorts *UDMServicesSbiNodePorts `json:"nodePorts,omitempty" yaml:"nodePorts,omitempty" mapstructure:"nodePorts,omitempty"`

	// Ports corresponds to the JSON schema field "ports".
	Ports *UDMServicesSbiPorts `json:"ports,omitempty" yaml:"ports,omitempty" mapstructure:"ports,omitempty"`

	// SessionAffinity corresponds to the JSON schema field "sessionAffinity".
	SessionAffinity *string `json:"sessionAffinity,omitempty" yaml:"sessionAffinity,omitempty" mapstructure:"sessionAffinity,omitempty"`

	// SessionAffinityConfig corresponds to the JSON schema field
	// "sessionAffinityConfig".
	SessionAffinityConfig map[string]interface{} `json:"sessionAffinityConfig,omitempty" yaml:"sessionAffinityConfig,omitempty" mapstructure:"sessionAffinityConfig,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

type UDMServicesSbiNodePorts struct {
	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *string `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type UDMServicesSbiPorts struct {
	// Sbi corresponds to the JSON schema field "sbi".
	Sbi *int `json:"sbi,omitempty" yaml:"sbi,omitempty" mapstructure:"sbi,omitempty"`
}

type UDMStartupProbe struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled *bool `json:"enabled,omitempty" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// FailureThreshold corresponds to the JSON schema field "failureThreshold".
	FailureThreshold *int `json:"failureThreshold,omitempty" yaml:"failureThreshold,omitempty" mapstructure:"failureThreshold,omitempty"`

	// InitialDelaySeconds corresponds to the JSON schema field "initialDelaySeconds".
	InitialDelaySeconds *int `json:"initialDelaySeconds,omitempty" yaml:"initialDelaySeconds,omitempty" mapstructure:"initialDelaySeconds,omitempty"`

	// PeriodSeconds corresponds to the JSON schema field "periodSeconds".
	PeriodSeconds *int `json:"periodSeconds,omitempty" yaml:"periodSeconds,omitempty" mapstructure:"periodSeconds,omitempty"`

	// SuccessThreshold corresponds to the JSON schema field "successThreshold".
	SuccessThreshold *int `json:"successThreshold,omitempty" yaml:"successThreshold,omitempty" mapstructure:"successThreshold,omitempty"`

	// TimeoutSeconds corresponds to the JSON schema field "timeoutSeconds".
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty" yaml:"timeoutSeconds,omitempty" mapstructure:"timeoutSeconds,omitempty"`
}

type UDMUpdateStrategy struct {
	// Type corresponds to the JSON schema field "type".
	Type *string `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}
