apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: slicer

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - mongo/

configMapGenerator:
  - name: slicer-env
    literals:
      # for monitor
      - MONARCH_THANOS_URL=http://datadist-thanos-query-frontend.monarch.svc.cluster.local:9065
      - MONARCH_REQUEST_TRANSLATOR_URI=http://request-translator-service.monarch.svc.cluster.local:7000
      - MONARCH_MONITORING_INTERVAL=1
      - MONITOR_TIMEOUT=255

      # for mongodb
      # MONGO_URI 从secret中构筑
      - MONGO_DB_NAME=slicer
      - MONGO_TIMEOUT=255

      # for kubernetes client
      - NAMESPACE=open5gs
      - MONITOR_NAMESPACE=monarch
      # KUBECONFIG_PATH=/home/sming/.kube/config (设置为空, 从集群中获取)

      # for http server
      - HTTP_SERVER_ADDRESS=0.0.0.0:30001

      # for render
      - TEMPLATE_PATH=render/template

      # for ipam
      - N3_NETWORK=10.10.3.0/24
      - N4_NETWORK=10.10.4.0/24
      - SESSION_NETWORK=10.32.0.0/11
      - SESSION_SUBNET_LENGTH=16
      - IPAM_TIMEOUT=255

      # for ai
      - MODEL_TYPE=ark
      - MODEL=deepseek-r1-250120
      - API_KEY=9aff57ec-30ed-4c28-bf8e-b215d198e5fc
          # 可选项
      - AI_TIMEOUT=255
      - BASE_URL=https://ark.cn-beijing.volces.com/api/v3
      - MaxTokens=4096

secretGenerator:
  - name: mongodb-secret
    literals:
      - USERNAME=admin
      - PASSWORD=admin

generatorOptions:
  disableNameSuffixHash: true # 禁用名称哈希后缀
