apiVersion: v1
kind: ServiceAccount
metadata:
  name: slicer-admin-sa
  namespace: slicer
  labels:
    app: slicer
    role: admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slicer-admin-binding
subjects:
  - kind: ServiceAccount
    name: slicer-admin-sa
    namespace: slicer # 必须与ServiceAccount所在命名空间一致
roleRef:
  kind: ClusterRole
  name: cluster-admin # Kubernetes内置最高权限ClusterRole
  apiGroup: rbac.authorization.k8s.io
