apiVersion: apps/v1
kind: Deployment
metadata:
  name: slicer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slicer
  template:
    metadata:
      labels:
        app: slicer
    spec:
      serviceAccountName: slicer-admin-sa
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.37
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              'until nc -z -v -w30 mongodb.slicer.svc.cluster.local 27017; do echo "Waiting for MongoDB..."; sleep 2; done; echo "MongoDB is up!"',
            ]
      containers:
        - name: slicer
          image: crpi-sut5dyyu9y5gqtfq.cn-shanghai.personal.cr.aliyuncs.com/sminggg/slicer:latest
          imagePullPolicy: Always
          command: ["./main"]
          ports:
            - containerPort: 58888
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: slicer-env
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: PASSWORD
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb.slicer.svc.cluster.local:27017/?authSource=admin"
