apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../open5gs

# images:
#   - name: ghcr.io/niloysh/open5gs
#     newTag: v2.7.0-upf-metrics-v2
images:
  - name: docker.io/shui12jiao/open5gs
    newName: ghcr.io/niloysh/open5gs
    newTag: v2.7.0-upf-metrics-v2
