apiVersion: v1
kind: Service
metadata:
  name: prom-exporter-service
  namespace: monarch
  labels:
    app: exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io.scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"  # which port should Prometheus scrape
spec:
  ports:
    - name: metrics
      port: 8000  # exposed port in pod
      targetPort: metrics  # port name in pod
  selector:
    app: exporter # target pods