apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open5gs

resources:
  - gnb-deployment.yaml
  - gnb-service.yaml

configMapGenerator:
  - name: gnb-configmap
    files:
      - open5gs-gnb.yaml
      - wrapper.sh

generatorOptions:
  disableNameSuffixHash: true
