apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monarch

resources:
  - otel-deployment.yaml
  - otel-service.yaml
  - otel-servicemonitor.yaml

configMapGenerator:
  - name: otel-configmap
    behavior: create
    files:
      - collector.yaml
    options:
      disableNameSuffixHash: true
