apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - upf-deployment.yaml

configMapGenerator:
  - name: upf1-configmap
    behavior: create
    files:
      - upfcfg.yaml
      - wrapper.sh
    options:
      labels:
        app: open5gs
        nf: upf
        name: upf1
