logger:
  file: /open5gs/install/var/log/open5gs/bsf.log

global:
  max:
    ue: 1024

bsf:
  sbi:
    server:
      - address: 127.0.0.15
        port: 80
    client:
      scp:
        - uri: http://127.0.1.10:80
