logger:
  file: /open5gs/install/var/log/open5gs/nrf.log

global:
  max:
    ue: 1024

nrf:
  serving:
    - plmn_id:
        mcc: 001
        mnc: 01

  sbi:
    server:
      - address: 127.0.0.10
        port: 80
