logger:
  file: /open5gs/install/var/log/open5gs/nssf.log

global:
  max:
    ue: 1024

nssf:
  sbi:
    server:
      - address: 127.0.0.14
        port: 80
    client:
      scp:
        - uri: http://127.0.1.10:80
      nsi:
        - uri: http://127.0.0.10:80
          s_nssai:
            sst: 1
            sd: 000001
        - uri: http://127.0.0.10:80
          s_nssai:
            sst: 2
            sd: 000002
