db_uri: mongodb://mongodb/open5gs

logger:
  file: /open5gs/install/var/log/open5gs/udr.log

global:
  max:
    ue: 1024
    
udr:
  sbi:
    server:
      - address: 127.0.0.20
        port: 80
    client:
      scp:
        - uri: http://127.0.1.10:80
