apiVersion: v1
kind: Service
metadata:
  name: request-translator-service
  namespace: monarch
  labels:
    app: monarch
    component: request-translator
spec:
  type: NodePort
  ports:
    - name: api # expose server port
      port: 7000 # which port is exposed
      targetPort: api # port name in pod
      nodePort: 30700
  selector:
    app: monarch # target pods
    component: request-translator
