// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sla": {
            "get": {
                "description": "获取系统内全部SLA列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SLA"
                ],
                "summary": "获取所有SLA",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SLA"
                            }
                        }
                    },
                    "500": {
                        "description": "获取失败/响应编码失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "接收SLA对象并创建新资源\nslice id对应切片必须存在",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SLA"
                ],
                "summary": "创建SLA",
                "parameters": [
                    {
                        "description": "SLA对象",
                        "name": "sla",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SLA"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功返回SLA对象",
                        "schema": {
                            "$ref": "#/definitions/model.SLA"
                        }
                    },
                    "400": {
                        "description": "请求解码失败/SLA已存在/参数非法",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "切片不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "存储失败/响应编码失败等服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sla/{slaId}": {
            "get": {
                "description": "根据SLA ID获取资源详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SLA"
                ],
                "summary": "获取单个SLA",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SLA ID",
                        "name": "slaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/model.SLA"
                        }
                    },
                    "400": {
                        "description": "缺少SLA ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "SLA不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "获取失败/响应编码失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "根据SLA ID更新资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SLA"
                ],
                "summary": "更新SLA",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SLA ID",
                        "name": "slaId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新后的SLA对象",
                        "name": "sla",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SLA"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功返回对象",
                        "schema": {
                            "$ref": "#/definitions/model.SLA"
                        }
                    },
                    "400": {
                        "description": "缺少SLA ID/请求解码失败/参数非法",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "SLA不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "更新失败/响应编码失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据SLA ID删除资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SLA"
                ],
                "summary": "删除SLA",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SLA ID",
                        "name": "slaId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "缺少SLA ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "SLA不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "删除失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/slice": {
            "get": {
                "description": "获取当前系统中的所有切片列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Slice"
                ],
                "summary": "获取所有切片",
                "responses": {
                    "200": {
                        "description": "获取成功，返回切片列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.SliceAndAddress"
                            }
                        }
                    },
                    "500": {
                        "description": "服务器内部错误（获取列表失败、响应编码失败）",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "接受一个切片对象，创建一个新的切片，并返回创建的切片对象",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Slice"
                ],
                "summary": "创建切片",
                "parameters": [
                    {
                        "description": "切片对象",
                        "name": "slice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Slice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功，返回切片及其地址",
                        "schema": {
                            "$ref": "#/definitions/model.SliceAndAddress"
                        }
                    },
                    "400": {
                        "description": "请求格式错误或参数非法",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "切片已存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误，如分配IP或部署资源失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/slice/{sliceId}": {
            "get": {
                "description": "根据切片ID获取指定切片的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Slice"
                ],
                "summary": "获取单个切片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "切片ID",
                        "name": "sliceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "$ref": "#/definitions/model.SliceAndAddress"
                        }
                    },
                    "400": {
                        "description": "缺少sliceId参数",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "切片不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误（获取失败、响应编码失败）",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据切片ID删除指定的切片资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Slice"
                ],
                "summary": "删除切片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "切片ID",
                        "name": "sliceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "删除成功无内容"
                    },
                    "400": {
                        "description": "缺少sliceId参数",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "切片不存在",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误（获取/渲染/删除k8s资源失败、释放IP失败、存储删除失败）",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AMBR": {
            "type": "object",
            "properties": {
                "downlink": {
                    "$ref": "#/definitions/model.BitRate"
                },
                "uplink": {
                    "$ref": "#/definitions/model.BitRate"
                }
            }
        },
        "model.ARP": {
            "type": "object",
            "properties": {
                "pre_emption_capability": {
                    "type": "integer"
                },
                "pre_emption_vulnerability": {
                    "type": "integer"
                },
                "priority_level": {
                    "type": "integer"
                }
            }
        },
        "model.BitRate": {
            "type": "object",
            "properties": {
                "unit": {
                    "type": "integer"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "model.Flow": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "direction": {
                    "type": "integer"
                }
            }
        },
        "model.GBR": {
            "type": "object",
            "properties": {
                "downlink": {
                    "$ref": "#/definitions/model.BitRate"
                },
                "uplink": {
                    "$ref": "#/definitions/model.BitRate"
                }
            }
        },
        "model.MBR": {
            "type": "object",
            "properties": {
                "downlink": {
                    "$ref": "#/definitions/model.BitRate"
                },
                "uplink": {
                    "$ref": "#/definitions/model.BitRate"
                }
            }
        },
        "model.PCCRule": {
            "type": "object",
            "properties": {
                "flow": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Flow"
                    }
                },
                "qos": {
                    "$ref": "#/definitions/model.QoS"
                }
            }
        },
        "model.QoS": {
            "type": "object",
            "properties": {
                "arp": {
                    "$ref": "#/definitions/model.ARP"
                },
                "gbr": {
                    "$ref": "#/definitions/model.GBR"
                },
                "index": {
                    "type": "integer"
                },
                "mbr": {
                    "$ref": "#/definitions/model.MBR"
                }
            }
        },
        "model.SLA": {
            "type": "object",
            "properties": {
                "availability": {
                    "description": "可用性",
                    "type": "number"
                },
                "down_bandwidth": {
                    "description": "下行带宽",
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "latency": {
                    "description": "延迟",
                    "type": "number"
                },
                "slice_id": {
                    "type": "string"
                },
                "up_bandwidth": {
                    "description": "上行带宽",
                    "type": "number"
                }
            }
        },
        "model.Session": {
            "type": "object",
            "properties": {
                "ambr": {
                    "$ref": "#/definitions/model.AMBR"
                },
                "name": {
                    "type": "string"
                },
                "pcc_rule": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PCCRule"
                    }
                },
                "qos": {
                    "$ref": "#/definitions/model.QoS"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "model.Slice": {
            "type": "object",
            "properties": {
                "default_indicator": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "sd": {
                    "type": "string"
                },
                "session": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Session"
                    }
                },
                "sst": {
                    "type": "integer"
                }
            }
        },
        "model.SliceAndAddress": {
            "type": "object",
            "properties": {
                "default_indicator": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "sd": {
                    "type": "string"
                },
                "session": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Session"
                    }
                },
                "sessionSubnets": {
                    "description": "Subnet是子网",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "smfn3Addr": {
                    "type": "string"
                },
                "smfn4Addr": {
                    "type": "string"
                },
                "sst": {
                    "type": "integer"
                },
                "upfn3Addr": {
                    "description": "Addr是地址",
                    "type": "string"
                },
                "upfn4Addr": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:30001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Slicer API",
	Description:      "Slicer API\n基于Kubernetes资源的切片管理系统API\n包括 切片管理 监控管理 性能保证 等功能",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
