apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - smf-deployment.yaml
  - smf-service.yaml

configMapGenerator:
  - name: smf1-configmap
    behavior: create
    files:
      - smfcfg.yaml

generatorOptions:
  disableNameSuffixHash: true
