apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - udm-deployment.yaml
  - udm-service.yaml

configMapGenerator:
  - name: udm-configmap
    behavior: create
    files:
      - udmcfg.yaml

generatorOptions:
  disableNameSuffixHash: true
