apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monarch

configMapGenerator:
  - name: monarch-dashboard-configmap
    behavior: create
    files:
      - dashboards/monarch-dashboard.json
    options:
      disableNameSuffixHash: true
generatorOptions:
  labels:
    grafana_dashboard: "1"